// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mojo/openapi/discriminator.proto

package mojo_openapi

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Discriminator struct {
	PropertyName         string   `protobuf:"bytes,1,opt,name=property_name,json=propertyName,proto3" json:"property_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Discriminator) Reset()         { *m = Discriminator{} }
func (m *Discriminator) String() string { return proto.CompactTextString(m) }
func (*Discriminator) ProtoMessage()    {}
func (*Discriminator) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4941eafe1e0f08e, []int{0}
}

func (m *Discriminator) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Discriminator.Unmarshal(m, b)
}
func (m *Discriminator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Discriminator.Marshal(b, m, deterministic)
}
func (m *Discriminator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Discriminator.Merge(m, src)
}
func (m *Discriminator) XXX_Size() int {
	return xxx_messageInfo_Discriminator.Size(m)
}
func (m *Discriminator) XXX_DiscardUnknown() {
	xxx_messageInfo_Discriminator.DiscardUnknown(m)
}

var xxx_messageInfo_Discriminator proto.InternalMessageInfo

func (m *Discriminator) GetPropertyName() string {
	if m != nil {
		return m.PropertyName
	}
	return ""
}

func init() {
	proto.RegisterType((*Discriminator)(nil), "mojo.openapi.Discriminator")
}

func init() { proto.RegisterFile("mojo/openapi/discriminator.proto", fileDescriptor_c4941eafe1e0f08e) }

var fileDescriptor_c4941eafe1e0f08e = []byte{
	// 108 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0xc8, 0xcd, 0xcf, 0xca,
	0xd7, 0xcf, 0x2f, 0x48, 0xcd, 0x4b, 0x2c, 0xc8, 0xd4, 0x4f, 0xc9, 0x2c, 0x4e, 0x2e, 0xca, 0xcc,
	0xcd, 0xcc, 0x4b, 0x2c, 0xc9, 0x2f, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x01, 0xa9,
	0xd0, 0x83, 0xaa, 0x50, 0x32, 0xe1, 0xe2, 0x75, 0x41, 0x56, 0x24, 0xa4, 0xcc, 0xc5, 0x5b, 0x50,
	0x94, 0x5f, 0x90, 0x5a, 0x54, 0x52, 0x19, 0x9f, 0x97, 0x98, 0x9b, 0x2a, 0xc1, 0xa8, 0xc0, 0xa8,
	0xc1, 0x19, 0xc4, 0x03, 0x13, 0xf4, 0x4b, 0xcc, 0x4d, 0x4d, 0x62, 0x03, 0x1b, 0x65, 0x0c, 0x08,
	0x00, 0x00, 0xff, 0xff, 0x33, 0xf0, 0xce, 0x89, 0x6e, 0x00, 0x00, 0x00,
}
