// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mojo/openapi/encoding.proto

package mojo_openapi

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Encoding struct {
	ContentType          string   `protobuf:"bytes,1,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Style                string   `protobuf:"bytes,3,opt,name=style,proto3" json:"style,omitempty"`
	Explode              bool     `protobuf:"varint,4,opt,name=explode,proto3" json:"explode,omitempty"`
	AllowReserved        bool     `protobuf:"varint,5,opt,name=allow_reserved,json=allowReserved,proto3" json:"allow_reserved,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Encoding) Reset()         { *m = Encoding{} }
func (m *Encoding) String() string { return proto.CompactTextString(m) }
func (*Encoding) ProtoMessage()    {}
func (*Encoding) Descriptor() ([]byte, []int) {
	return fileDescriptor_52a8b385154c4336, []int{0}
}

func (m *Encoding) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Encoding.Unmarshal(m, b)
}
func (m *Encoding) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Encoding.Marshal(b, m, deterministic)
}
func (m *Encoding) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Encoding.Merge(m, src)
}
func (m *Encoding) XXX_Size() int {
	return xxx_messageInfo_Encoding.Size(m)
}
func (m *Encoding) XXX_DiscardUnknown() {
	xxx_messageInfo_Encoding.DiscardUnknown(m)
}

var xxx_messageInfo_Encoding proto.InternalMessageInfo

func (m *Encoding) GetContentType() string {
	if m != nil {
		return m.ContentType
	}
	return ""
}

func (m *Encoding) GetStyle() string {
	if m != nil {
		return m.Style
	}
	return ""
}

func (m *Encoding) GetExplode() bool {
	if m != nil {
		return m.Explode
	}
	return false
}

func (m *Encoding) GetAllowReserved() bool {
	if m != nil {
		return m.AllowReserved
	}
	return false
}

func init() {
	proto.RegisterType((*Encoding)(nil), "mojo.openapi.Encoding")
}

func init() { proto.RegisterFile("mojo/openapi/encoding.proto", fileDescriptor_52a8b385154c4336) }

var fileDescriptor_52a8b385154c4336 = []byte{
	// 165 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0x8e, 0xb1, 0x0a, 0xc2, 0x30,
	0x14, 0x45, 0x09, 0x5a, 0xad, 0xcf, 0xea, 0x10, 0x1c, 0x02, 0x2e, 0x55, 0x10, 0x3a, 0xb5, 0x83,
	0xdf, 0xe0, 0x0f, 0x14, 0xf7, 0x52, 0xdb, 0x87, 0x54, 0x62, 0xde, 0x23, 0x0d, 0x6a, 0x76, 0x3f,
	0x5c, 0x8c, 0x71, 0xbc, 0xe7, 0x9c, 0xe1, 0xc2, 0xf6, 0x4e, 0x37, 0xaa, 0x88, 0xd1, 0xb4, 0x3c,
	0x54, 0x68, 0x3a, 0xea, 0x07, 0x73, 0x2d, 0xd9, 0x92, 0x23, 0x99, 0x7d, 0x65, 0x19, 0xe5, 0xfe,
	0x2d, 0x20, 0x3d, 0xc5, 0x40, 0xee, 0x20, 0xeb, 0xc8, 0x38, 0x34, 0xae, 0x71, 0x9e, 0x51, 0x89,
	0x5c, 0x14, 0x8b, 0x7a, 0x19, 0xd9, 0xd9, 0x33, 0xca, 0x0d, 0x24, 0xa3, 0xf3, 0x1a, 0xd5, 0x24,
	0xb8, 0xdf, 0x90, 0x0a, 0xe6, 0xf8, 0x62, 0x4d, 0x3d, 0xaa, 0x69, 0x2e, 0x8a, 0xb4, 0xfe, 0x4f,
	0x79, 0x80, 0x75, 0xab, 0x35, 0x3d, 0x1b, 0x8b, 0x23, 0xda, 0x07, 0xf6, 0x2a, 0x09, 0xc1, 0x2a,
	0xd0, 0x3a, 0xc2, 0xcb, 0x2c, 0x7c, 0x3b, 0x7e, 0x02, 0x00, 0x00, 0xff, 0xff, 0xd7, 0xc5, 0x55,
	0x95, 0xba, 0x00, 0x00, 0x00,
}
