// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mojo/openapi/openapi.proto

package mojo_openapi

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type OpenAPI struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OpenAPI) Reset()         { *m = OpenAPI{} }
func (m *OpenAPI) String() string { return proto.CompactTextString(m) }
func (*OpenAPI) ProtoMessage()    {}
func (*OpenAPI) Descriptor() ([]byte, []int) {
	return fileDescriptor_67b73ac0892fabb6, []int{0}
}

func (m *OpenAPI) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpenAPI.Unmarshal(m, b)
}
func (m *OpenAPI) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpenAPI.Marshal(b, m, deterministic)
}
func (m *OpenAPI) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpenAPI.Merge(m, src)
}
func (m *OpenAPI) XXX_Size() int {
	return xxx_messageInfo_OpenAPI.Size(m)
}
func (m *OpenAPI) XXX_DiscardUnknown() {
	xxx_messageInfo_OpenAPI.DiscardUnknown(m)
}

var xxx_messageInfo_OpenAPI proto.InternalMessageInfo

func init() {
	proto.RegisterType((*OpenAPI)(nil), "mojo.openapi.OpenAPI")
}

func init() { proto.RegisterFile("mojo/openapi/openapi.proto", fileDescriptor_67b73ac0892fabb6) }

var fileDescriptor_67b73ac0892fabb6 = []byte{
	// 68 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0xca, 0xcd, 0xcf, 0xca,
	0xd7, 0xcf, 0x2f, 0x48, 0xcd, 0x4b, 0x2c, 0xc8, 0x84, 0xd1, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9,
	0x42, 0x3c, 0x20, 0x39, 0x3d, 0xa8, 0x98, 0x12, 0x27, 0x17, 0xbb, 0x7f, 0x41, 0x6a, 0x9e, 0x63,
	0x80, 0x67, 0x12, 0x1b, 0x58, 0xde, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x58, 0xc0, 0x07, 0x08,
	0x3d, 0x00, 0x00, 0x00,
}
