// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mojo/openapi/security_scheme.proto

package mojo_openapi

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SecurityScheme_Type int32

const (
	SecurityScheme_api_key         SecurityScheme_Type = 0
	SecurityScheme_http            SecurityScheme_Type = 1
	SecurityScheme_oauth2          SecurityScheme_Type = 2
	SecurityScheme_open_id_connect SecurityScheme_Type = 3
)

var SecurityScheme_Type_name = map[int32]string{
	0: "api_key",
	1: "http",
	2: "oauth2",
	3: "open_id_connect",
}

var SecurityScheme_Type_value = map[string]int32{
	"api_key":         0,
	"http":            1,
	"oauth2":          2,
	"open_id_connect": 3,
}

func (x SecurityScheme_Type) String() string {
	return proto.EnumName(SecurityScheme_Type_name, int32(x))
}

func (SecurityScheme_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_27b8a3ba7ed677a4, []int{0, 0}
}

type SecurityScheme struct {
	Name                 string   `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	In                   string   `protobuf:"bytes,6,opt,name=in,proto3" json:"in,omitempty"`
	Scheme               string   `protobuf:"bytes,10,opt,name=scheme,proto3" json:"scheme,omitempty"`
	BearerFormat         string   `protobuf:"bytes,11,opt,name=bearer_format,json=bearerFormat,proto3" json:"bearer_format,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SecurityScheme) Reset()         { *m = SecurityScheme{} }
func (m *SecurityScheme) String() string { return proto.CompactTextString(m) }
func (*SecurityScheme) ProtoMessage()    {}
func (*SecurityScheme) Descriptor() ([]byte, []int) {
	return fileDescriptor_27b8a3ba7ed677a4, []int{0}
}

func (m *SecurityScheme) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SecurityScheme.Unmarshal(m, b)
}
func (m *SecurityScheme) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SecurityScheme.Marshal(b, m, deterministic)
}
func (m *SecurityScheme) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SecurityScheme.Merge(m, src)
}
func (m *SecurityScheme) XXX_Size() int {
	return xxx_messageInfo_SecurityScheme.Size(m)
}
func (m *SecurityScheme) XXX_DiscardUnknown() {
	xxx_messageInfo_SecurityScheme.DiscardUnknown(m)
}

var xxx_messageInfo_SecurityScheme proto.InternalMessageInfo

func (m *SecurityScheme) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SecurityScheme) GetIn() string {
	if m != nil {
		return m.In
	}
	return ""
}

func (m *SecurityScheme) GetScheme() string {
	if m != nil {
		return m.Scheme
	}
	return ""
}

func (m *SecurityScheme) GetBearerFormat() string {
	if m != nil {
		return m.BearerFormat
	}
	return ""
}

func init() {
	proto.RegisterEnum("mojo.openapi.SecurityScheme_Type", SecurityScheme_Type_name, SecurityScheme_Type_value)
	proto.RegisterType((*SecurityScheme)(nil), "mojo.openapi.SecurityScheme")
}

func init() { proto.RegisterFile("mojo/openapi/security_scheme.proto", fileDescriptor_27b8a3ba7ed677a4) }

var fileDescriptor_27b8a3ba7ed677a4 = []byte{
	// 204 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x2c, 0x8f, 0xb1, 0x4e, 0xc4, 0x30,
	0x0c, 0x86, 0x69, 0x29, 0x01, 0x7c, 0xc7, 0x11, 0x19, 0x09, 0x65, 0x44, 0x65, 0x61, 0xba, 0x93,
	0x60, 0x67, 0xe4, 0x01, 0x28, 0x7b, 0x94, 0x06, 0xa3, 0x06, 0x94, 0x38, 0x4a, 0xd3, 0xa1, 0x8f,
	0xc5, 0x1b, 0x9e, 0x9a, 0x76, 0xb3, 0x3f, 0x7f, 0xb2, 0xfe, 0x1f, 0x5a, 0xcf, 0xbf, 0x7c, 0xe2,
	0x48, 0xc1, 0x44, 0x77, 0x1a, 0xc9, 0x4e, 0xc9, 0xe5, 0x59, 0x8f, 0x76, 0x20, 0x4f, 0xc7, 0x98,
	0x38, 0x33, 0xee, 0x17, 0xe7, 0xb8, 0x39, 0xed, 0x7f, 0x05, 0x87, 0x6e, 0xf3, 0xba, 0xa2, 0x21,
	0x42, 0x13, 0x8c, 0x27, 0x75, 0xf5, 0x54, 0xbd, 0xdc, 0x7e, 0x96, 0x19, 0x0f, 0x50, 0xbb, 0xa0,
	0x44, 0x21, 0xb5, 0x0b, 0xf8, 0x08, 0x62, 0x7d, 0xaa, 0xa0, 0xb0, 0x6d, 0xc3, 0x67, 0xb8, 0xeb,
	0xc9, 0x24, 0x4a, 0xfa, 0x87, 0x93, 0x37, 0x59, 0xed, 0xca, 0x79, 0xbf, 0xc2, 0x8f, 0xc2, 0xda,
	0x77, 0x68, 0xbe, 0xe6, 0x48, 0xb8, 0x83, 0x6b, 0x13, 0x9d, 0xfe, 0xa3, 0x59, 0x5e, 0xe0, 0x0d,
	0x34, 0x43, 0xce, 0x51, 0x56, 0x08, 0x20, 0xd8, 0x4c, 0x79, 0x78, 0x95, 0x35, 0x3e, 0xc0, 0xfd,
	0x92, 0x54, 0xbb, 0x6f, 0x6d, 0x39, 0x04, 0xb2, 0x59, 0x5e, 0xf6, 0xa2, 0x14, 0x79, 0x3b, 0x07,
	0x00, 0x00, 0xff, 0xff, 0x54, 0x21, 0xdb, 0xfc, 0xee, 0x00, 0x00, 0x00,
}
