// Code generated by mojo. DO NOT EDIT.
// Rerunning mojo will overwrite this file.
//
// Copyright 2021 Mojo-lang.org
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package openapi

import (
	"strconv"
)

var ExpressionTypeNames = map[int32]string{
	1: "url",
	2: "method",
	3: "statusCode",
	4: "request",
	5: "source",
	6: "response",
}

var ExpressionTypeValues = map[string]Expression_Type{
	"url":        Expression_TYPE_URL,
	"method":     Expression_TYPE_METHOD,
	"statusCode": Expression_TYPE_STATUS_CODE,
	"request":    Expression_TYPE_REQUEST,
	"source":     Expression_TYPE_SOURCE,
	"response":   Expression_TYPE_RESPONSE,
}

func (x Expression_Type) Format() string {
	s, ok := ExpressionTypeNames[int32(x)]
	if ok {
		return s
	}
	if int(x) == 0 {
		return "unspecified"
	}
	return strconv.Itoa(int(x))
}

func (x Expression_Type) ToString() string {
	return x.Format()
}

func (x *Expression_Type) Parse(value string) error {
	if x != nil {
		s, ok := ExpressionTypeValues[value]
		if ok {
			*x = s
		} else {
			*x = Expression_TYPE_URL
		}
	} else {
		*x = Expression_TYPE_URL
	}
	return nil
}

func ParseExpression_Type(value string) (Expression_Type, error) {
	var v Expression_Type
	if err := (&v).Parse(value); err != nil {
		return v, err
	}
	return v, nil
}
