// Code generated by mojo. DO NOT EDIT.
// Rerunning mojo will overwrite this file.
//
// Copyright 2021 Mojo-lang.org
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package openapi

import (
	"strconv"
)

var ExpressionLocationNames = map[int32]string{
	1: "path",
	2: "query",
	3: "header",
	5: "body",
}

var ExpressionLocationValues = map[string]Expression_Location{
	"path":   Expression_LOCATION_PATH,
	"query":  Expression_LOCATION_QUERY,
	"header": Expression_LOCATION_HEADER,
	"body":   Expression_LOCATION_BODY,
}

func (x Expression_Location) Format() string {
	s, ok := ExpressionLocationNames[int32(x)]
	if ok {
		return s
	}
	if int(x) == 0 {
		return "unspecified"
	}
	return strconv.Itoa(int(x))
}

func (x Expression_Location) ToString() string {
	return x.Format()
}

func (x *Expression_Location) Parse(value string) error {
	if x != nil {
		s, ok := ExpressionLocationValues[value]
		if ok {
			*x = s
		} else {
			*x = Expression_LOCATION_PATH
		}
	} else {
		*x = Expression_LOCATION_PATH
	}
	return nil
}

func ParseExpression_Location(value string) (Expression_Location, error) {
	var v Expression_Location
	if err := (&v).Parse(value); err != nil {
		return v, err
	}
	return v, nil
}
