// Code generated by wand. DO NOT EDIT.
// Rerunning wand will overwrite this file.
//
// Copyright 2021 Mojo-lang.org
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package openapi

import (
	"strconv"
)

var ParameterStyleNames = map[int32]string{
	1: "matrix",
	2: "label",
	3: "form",
	4: "simple",
	5: "space_delimited",
	6: "pipe_delimited",
	7: "deep_object",
}

var ParameterStyleValues = map[string]Parameter_Style{
	"matrix":          Parameter_STYLE_MATRIX,
	"label":           Parameter_STYLE_LABEL,
	"form":            Parameter_STYLE_FORM,
	"simple":          Parameter_STYLE_SIMPLE,
	"space_delimited": Parameter_STYLE_SPACE_DELIMITED,
	"pipe_delimited":  Parameter_STYLE_PIPE_DELIMITED,
	"deep_object":     Parameter_STYLE_DEEP_OBJECT,
}

func (x Parameter_Style) Format() string {
	s, ok := ParameterStyleNames[int32(x)]
	if ok {
		return s
	}
	if int(x) == 0 {
		return "unspecified"
	}
	return strconv.Itoa(int(x))
}

func (x *Parameter_Style) Parse(value string) {
	if x != nil {
		s, ok := ParameterStyleValues[value]
		if ok {
			*x = s
		} else {
			*x = Parameter_STYLE_MATRIX
		}
	} else {
		*x = Parameter_STYLE_MATRIX
	}
}
