// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mojo/openapi/referenceable_link.proto

package openapi

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ReferenceableLink struct {
	// Types that are valid to be assigned to ReferenceableLink:
	//	*ReferenceableLink_Reference
	//	*ReferenceableLink_Link
	ReferenceableLink    isReferenceableLink_ReferenceableLink `protobuf_oneof:"referenceable_link"`
	XXX_NoUnkeyedLiteral struct{}                              `json:"-" gorm:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte                                `json:"-" gorm:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32                                 `json:"-" gorm:"-" xml:"-" bson:"-"`
}

func (m *ReferenceableLink) Reset()         { *m = ReferenceableLink{} }
func (m *ReferenceableLink) String() string { return proto.CompactTextString(m) }
func (*ReferenceableLink) ProtoMessage()    {}
func (*ReferenceableLink) Descriptor() ([]byte, []int) {
	return fileDescriptor_80f86c3d26d95f7a, []int{0}
}
func (m *ReferenceableLink) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReferenceableLink.Unmarshal(m, b)
}
func (m *ReferenceableLink) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReferenceableLink.Marshal(b, m, deterministic)
}
func (m *ReferenceableLink) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReferenceableLink.Merge(m, src)
}
func (m *ReferenceableLink) XXX_Size() int {
	return xxx_messageInfo_ReferenceableLink.Size(m)
}
func (m *ReferenceableLink) XXX_DiscardUnknown() {
	xxx_messageInfo_ReferenceableLink.DiscardUnknown(m)
}

var xxx_messageInfo_ReferenceableLink proto.InternalMessageInfo

type isReferenceableLink_ReferenceableLink interface {
	isReferenceableLink_ReferenceableLink()
}

type ReferenceableLink_Reference struct {
	Reference *Reference `protobuf:"bytes,1,opt,name=reference,proto3,oneof" json:"reference,omitempty"`
}
type ReferenceableLink_Link struct {
	Link *Link `protobuf:"bytes,2,opt,name=link,proto3,oneof" json:"link,omitempty"`
}

func (*ReferenceableLink_Reference) isReferenceableLink_ReferenceableLink() {}
func (*ReferenceableLink_Link) isReferenceableLink_ReferenceableLink()      {}

func (m *ReferenceableLink) GetReferenceableLink() isReferenceableLink_ReferenceableLink {
	if m != nil {
		return m.ReferenceableLink
	}
	return nil
}

func (m *ReferenceableLink) GetReference() *Reference {
	if x, ok := m.GetReferenceableLink().(*ReferenceableLink_Reference); ok {
		return x.Reference
	}
	return nil
}

func (m *ReferenceableLink) GetLink() *Link {
	if x, ok := m.GetReferenceableLink().(*ReferenceableLink_Link); ok {
		return x.Link
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ReferenceableLink) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ReferenceableLink_Reference)(nil),
		(*ReferenceableLink_Link)(nil),
	}
}

func init() {
	proto.RegisterType((*ReferenceableLink)(nil), "mojo.openapi.ReferenceableLink")
}

func init() {
	proto.RegisterFile("mojo/openapi/referenceable_link.proto", fileDescriptor_80f86c3d26d95f7a)
}

var fileDescriptor_80f86c3d26d95f7a = []byte{
	// 240 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0xcd, 0xcd, 0xcf, 0xca,
	0xd7, 0xcf, 0x2f, 0x48, 0xcd, 0x4b, 0x2c, 0xc8, 0xd4, 0x2f, 0x4a, 0x4d, 0x4b, 0x2d, 0x4a, 0xcd,
	0x4b, 0x4e, 0x4d, 0x4c, 0xca, 0x49, 0x8d, 0xcf, 0xc9, 0xcc, 0xcb, 0xd6, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x17, 0xe2, 0x01, 0x29, 0xd3, 0x83, 0x2a, 0x93, 0x12, 0x47, 0xd1, 0x84, 0x50, 0x26, 0x25,
	0x83, 0xdd, 0x34, 0x88, 0xac, 0xd2, 0x4e, 0x46, 0x2e, 0xc1, 0x20, 0x64, 0x1b, 0x7c, 0x32, 0xf3,
	0xb2, 0x85, 0x02, 0xb8, 0x38, 0xe1, 0x0a, 0x25, 0x18, 0x15, 0x18, 0x35, 0xb8, 0x8d, 0xc4, 0xf5,
	0x90, 0xad, 0xd3, 0x83, 0xeb, 0x71, 0x12, 0x7f, 0x75, 0x4f, 0x5e, 0x18, 0xae, 0x5a, 0x27, 0x3f,
	0x37, 0xb3, 0x24, 0x35, 0xb7, 0xa0, 0xa4, 0xd2, 0x83, 0x21, 0x08, 0x61, 0x88, 0x90, 0x0d, 0x17,
	0x0b, 0xc8, 0x4d, 0x12, 0x4c, 0x60, 0xc3, 0x84, 0x50, 0x0d, 0x03, 0xd9, 0xe9, 0x24, 0xf4, 0xea,
	0x9e, 0x3c, 0x1f, 0x48, 0x0d, 0x8a, 0x11, 0x60, 0x5d, 0x4e, 0x22, 0x5c, 0x42, 0x98, 0xc1, 0xe0,
	0x54, 0x3c, 0xe3, 0xb1, 0x1c, 0x03, 0x97, 0x64, 0x7e, 0x51, 0x3a, 0xd8, 0xb8, 0x9c, 0xc4, 0xbc,
	0x74, 0x14, 0x73, 0x9d, 0xc4, 0x30, 0x7c, 0x16, 0x00, 0xf2, 0x74, 0x00, 0x63, 0x94, 0x45, 0x7a,
	0x66, 0x49, 0x46, 0x69, 0x92, 0x5e, 0x72, 0x7e, 0xae, 0x3e, 0x48, 0x8b, 0x2e, 0x48, 0x33, 0x3c,
	0x90, 0xd2, 0xf3, 0xf5, 0x0b, 0xb2, 0xd3, 0xf5, 0x91, 0x03, 0xce, 0x1a, 0x4a, 0x27, 0xb1, 0x81,
	0xc3, 0xcd, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x70, 0x69, 0xdc, 0xf7, 0xa5, 0x01, 0x00, 0x00,
}
