// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mojo/openapi/referenceable_security_scheme.proto

package openapi

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ReferenceableSecurityScheme struct {
	// Types that are valid to be assigned to ReferenceableSecurityScheme:
	//	*ReferenceableSecurityScheme_Reference
	//	*ReferenceableSecurityScheme_SecurityScheme
	ReferenceableSecurityScheme isReferenceableSecurityScheme_ReferenceableSecurityScheme `protobuf_oneof:"referenceable_security_scheme"`
	XXX_NoUnkeyedLiteral        struct{}                                                  `json:"-"`
	XXX_unrecognized            []byte                                                    `json:"-"`
	XXX_sizecache               int32                                                     `json:"-"`
}

func (m *ReferenceableSecurityScheme) Reset()         { *m = ReferenceableSecurityScheme{} }
func (m *ReferenceableSecurityScheme) String() string { return proto.CompactTextString(m) }
func (*ReferenceableSecurityScheme) ProtoMessage()    {}
func (*ReferenceableSecurityScheme) Descriptor() ([]byte, []int) {
	return fileDescriptor_bce8d0acd5306edf, []int{0}
}
func (m *ReferenceableSecurityScheme) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReferenceableSecurityScheme.Unmarshal(m, b)
}
func (m *ReferenceableSecurityScheme) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReferenceableSecurityScheme.Marshal(b, m, deterministic)
}
func (m *ReferenceableSecurityScheme) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReferenceableSecurityScheme.Merge(m, src)
}
func (m *ReferenceableSecurityScheme) XXX_Size() int {
	return xxx_messageInfo_ReferenceableSecurityScheme.Size(m)
}
func (m *ReferenceableSecurityScheme) XXX_DiscardUnknown() {
	xxx_messageInfo_ReferenceableSecurityScheme.DiscardUnknown(m)
}

var xxx_messageInfo_ReferenceableSecurityScheme proto.InternalMessageInfo

type isReferenceableSecurityScheme_ReferenceableSecurityScheme interface {
	isReferenceableSecurityScheme_ReferenceableSecurityScheme()
}

type ReferenceableSecurityScheme_Reference struct {
	Reference *Reference `protobuf:"bytes,1,opt,name=reference,proto3,oneof" json:"reference,omitempty"`
}
type ReferenceableSecurityScheme_SecurityScheme struct {
	SecurityScheme *SecurityScheme `protobuf:"bytes,2,opt,name=security_scheme,json=securityScheme,proto3,oneof" json:"securityScheme,omitempty"`
}

func (*ReferenceableSecurityScheme_Reference) isReferenceableSecurityScheme_ReferenceableSecurityScheme() {
}
func (*ReferenceableSecurityScheme_SecurityScheme) isReferenceableSecurityScheme_ReferenceableSecurityScheme() {
}

func (m *ReferenceableSecurityScheme) GetReferenceableSecurityScheme() isReferenceableSecurityScheme_ReferenceableSecurityScheme {
	if m != nil {
		return m.ReferenceableSecurityScheme
	}
	return nil
}

func (m *ReferenceableSecurityScheme) GetReference() *Reference {
	if x, ok := m.GetReferenceableSecurityScheme().(*ReferenceableSecurityScheme_Reference); ok {
		return x.Reference
	}
	return nil
}

func (m *ReferenceableSecurityScheme) GetSecurityScheme() *SecurityScheme {
	if x, ok := m.GetReferenceableSecurityScheme().(*ReferenceableSecurityScheme_SecurityScheme); ok {
		return x.SecurityScheme
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ReferenceableSecurityScheme) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ReferenceableSecurityScheme_Reference)(nil),
		(*ReferenceableSecurityScheme_SecurityScheme)(nil),
	}
}

func init() {
	proto.RegisterType((*ReferenceableSecurityScheme)(nil), "mojo.openapi.ReferenceableSecurityScheme")
}

func init() {
	proto.RegisterFile("mojo/openapi/referenceable_security_scheme.proto", fileDescriptor_bce8d0acd5306edf)
}

var fileDescriptor_bce8d0acd5306edf = []byte{
	// 253 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x32, 0xc8, 0xcd, 0xcf, 0xca,
	0xd7, 0xcf, 0x2f, 0x48, 0xcd, 0x4b, 0x2c, 0xc8, 0xd4, 0x2f, 0x4a, 0x4d, 0x4b, 0x2d, 0x4a, 0xcd,
	0x4b, 0x4e, 0x4d, 0x4c, 0xca, 0x49, 0x8d, 0x2f, 0x4e, 0x4d, 0x2e, 0x2d, 0xca, 0x2c, 0xa9, 0x8c,
	0x2f, 0x4e, 0xce, 0x48, 0xcd, 0x4d, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x01, 0xe9,
	0xd0, 0x83, 0xea, 0x90, 0x92, 0xc1, 0xae, 0x1f, 0xa2, 0x56, 0x4a, 0x09, 0x45, 0x16, 0xab, 0x79,
	0x4a, 0xdf, 0x19, 0xb9, 0xa4, 0x83, 0x90, 0xed, 0x0d, 0x86, 0x2a, 0x0b, 0x06, 0xab, 0x12, 0x0a,
	0xe0, 0xe2, 0x84, 0x1b, 0x2b, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x6d, 0x24, 0xae, 0x87, 0xec, 0x06,
	0x3d, 0xb8, 0x6e, 0x27, 0xf1, 0x57, 0xf7, 0xe4, 0x85, 0xe1, 0xaa, 0x75, 0xf2, 0x73, 0x33, 0x4b,
	0x52, 0x73, 0x0b, 0x4a, 0x2a, 0x3d, 0x18, 0x82, 0x10, 0x86, 0x08, 0xa5, 0x72, 0xf1, 0xa3, 0x39,
	0x45, 0x82, 0x09, 0x6c, 0xae, 0x0c, 0xaa, 0xb9, 0xa8, 0x0e, 0x71, 0x92, 0x79, 0x75, 0x4f, 0x5e,
	0xa2, 0x18, 0x45, 0x0c, 0xc5, 0x06, 0x3e, 0x54, 0x39, 0x27, 0x79, 0x2e, 0x59, 0xbc, 0xe1, 0xe9,
	0x54, 0xc9, 0x25, 0x99, 0x5f, 0x94, 0x0e, 0xb6, 0x33, 0x27, 0x31, 0x2f, 0x1d, 0xc5, 0x72, 0x27,
	0x05, 0x3c, 0x61, 0x12, 0x00, 0x0a, 0xb8, 0x00, 0xc6, 0x28, 0x8b, 0xf4, 0xcc, 0x92, 0x8c, 0xd2,
	0x24, 0xbd, 0xe4, 0xfc, 0x5c, 0x7d, 0x90, 0x66, 0x5d, 0x90, 0x31, 0xf0, 0xe0, 0x4e, 0xcf, 0xd7,
	0x2f, 0xc8, 0x4e, 0xd7, 0x47, 0x8e, 0x02, 0x6b, 0x28, 0x9d, 0xc4, 0x06, 0x0e, 0x7b, 0x63, 0x40,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xb7, 0x1f, 0xfc, 0x40, 0xff, 0x01, 0x00, 0x00,
}
