// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/openapi/oauth_flows.proto

package org.mojolang.mojo.openapi;

/**
 * Protobuf type {@code mojo.openapi.OAuthFlows}
 */
public final class OAuthFlows extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:mojo.openapi.OAuthFlows)
    OAuthFlowsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use OAuthFlows.newBuilder() to construct.
  private OAuthFlows(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private OAuthFlows() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new OAuthFlows();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private OAuthFlows(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            org.mojolang.mojo.openapi.OAuthFlow.Builder subBuilder = null;
            if (implicit_ != null) {
              subBuilder = implicit_.toBuilder();
            }
            implicit_ = input.readMessage(org.mojolang.mojo.openapi.OAuthFlow.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(implicit_);
              implicit_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            org.mojolang.mojo.openapi.OAuthFlow.Builder subBuilder = null;
            if (password_ != null) {
              subBuilder = password_.toBuilder();
            }
            password_ = input.readMessage(org.mojolang.mojo.openapi.OAuthFlow.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(password_);
              password_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            org.mojolang.mojo.openapi.OAuthFlow.Builder subBuilder = null;
            if (clientCredentials_ != null) {
              subBuilder = clientCredentials_.toBuilder();
            }
            clientCredentials_ = input.readMessage(org.mojolang.mojo.openapi.OAuthFlow.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(clientCredentials_);
              clientCredentials_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            org.mojolang.mojo.openapi.OAuthFlow.Builder subBuilder = null;
            if (authorizationCode_ != null) {
              subBuilder = authorizationCode_.toBuilder();
            }
            authorizationCode_ = input.readMessage(org.mojolang.mojo.openapi.OAuthFlow.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(authorizationCode_);
              authorizationCode_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.mojolang.mojo.openapi.OauthFlowsProto.internal_static_mojo_openapi_OAuthFlows_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.mojolang.mojo.openapi.OauthFlowsProto.internal_static_mojo_openapi_OAuthFlows_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.mojolang.mojo.openapi.OAuthFlows.class, org.mojolang.mojo.openapi.OAuthFlows.Builder.class);
  }

  public static final int IMPLICIT_FIELD_NUMBER = 1;
  private org.mojolang.mojo.openapi.OAuthFlow implicit_;
  /**
   * <code>.mojo.openapi.OAuthFlow implicit = 1;</code>
   * @return Whether the implicit field is set.
   */
  @java.lang.Override
  public boolean hasImplicit() {
    return implicit_ != null;
  }
  /**
   * <code>.mojo.openapi.OAuthFlow implicit = 1;</code>
   * @return The implicit.
   */
  @java.lang.Override
  public org.mojolang.mojo.openapi.OAuthFlow getImplicit() {
    return implicit_ == null ? org.mojolang.mojo.openapi.OAuthFlow.getDefaultInstance() : implicit_;
  }
  /**
   * <code>.mojo.openapi.OAuthFlow implicit = 1;</code>
   */
  @java.lang.Override
  public org.mojolang.mojo.openapi.OAuthFlowOrBuilder getImplicitOrBuilder() {
    return getImplicit();
  }

  public static final int PASSWORD_FIELD_NUMBER = 2;
  private org.mojolang.mojo.openapi.OAuthFlow password_;
  /**
   * <code>.mojo.openapi.OAuthFlow password = 2;</code>
   * @return Whether the password field is set.
   */
  @java.lang.Override
  public boolean hasPassword() {
    return password_ != null;
  }
  /**
   * <code>.mojo.openapi.OAuthFlow password = 2;</code>
   * @return The password.
   */
  @java.lang.Override
  public org.mojolang.mojo.openapi.OAuthFlow getPassword() {
    return password_ == null ? org.mojolang.mojo.openapi.OAuthFlow.getDefaultInstance() : password_;
  }
  /**
   * <code>.mojo.openapi.OAuthFlow password = 2;</code>
   */
  @java.lang.Override
  public org.mojolang.mojo.openapi.OAuthFlowOrBuilder getPasswordOrBuilder() {
    return getPassword();
  }

  public static final int CLIENT_CREDENTIALS_FIELD_NUMBER = 3;
  private org.mojolang.mojo.openapi.OAuthFlow clientCredentials_;
  /**
   * <code>.mojo.openapi.OAuthFlow client_credentials = 3;</code>
   * @return Whether the clientCredentials field is set.
   */
  @java.lang.Override
  public boolean hasClientCredentials() {
    return clientCredentials_ != null;
  }
  /**
   * <code>.mojo.openapi.OAuthFlow client_credentials = 3;</code>
   * @return The clientCredentials.
   */
  @java.lang.Override
  public org.mojolang.mojo.openapi.OAuthFlow getClientCredentials() {
    return clientCredentials_ == null ? org.mojolang.mojo.openapi.OAuthFlow.getDefaultInstance() : clientCredentials_;
  }
  /**
   * <code>.mojo.openapi.OAuthFlow client_credentials = 3;</code>
   */
  @java.lang.Override
  public org.mojolang.mojo.openapi.OAuthFlowOrBuilder getClientCredentialsOrBuilder() {
    return getClientCredentials();
  }

  public static final int AUTHORIZATION_CODE_FIELD_NUMBER = 4;
  private org.mojolang.mojo.openapi.OAuthFlow authorizationCode_;
  /**
   * <code>.mojo.openapi.OAuthFlow authorization_code = 4;</code>
   * @return Whether the authorizationCode field is set.
   */
  @java.lang.Override
  public boolean hasAuthorizationCode() {
    return authorizationCode_ != null;
  }
  /**
   * <code>.mojo.openapi.OAuthFlow authorization_code = 4;</code>
   * @return The authorizationCode.
   */
  @java.lang.Override
  public org.mojolang.mojo.openapi.OAuthFlow getAuthorizationCode() {
    return authorizationCode_ == null ? org.mojolang.mojo.openapi.OAuthFlow.getDefaultInstance() : authorizationCode_;
  }
  /**
   * <code>.mojo.openapi.OAuthFlow authorization_code = 4;</code>
   */
  @java.lang.Override
  public org.mojolang.mojo.openapi.OAuthFlowOrBuilder getAuthorizationCodeOrBuilder() {
    return getAuthorizationCode();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (implicit_ != null) {
      output.writeMessage(1, getImplicit());
    }
    if (password_ != null) {
      output.writeMessage(2, getPassword());
    }
    if (clientCredentials_ != null) {
      output.writeMessage(3, getClientCredentials());
    }
    if (authorizationCode_ != null) {
      output.writeMessage(4, getAuthorizationCode());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (implicit_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getImplicit());
    }
    if (password_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getPassword());
    }
    if (clientCredentials_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getClientCredentials());
    }
    if (authorizationCode_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getAuthorizationCode());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.mojolang.mojo.openapi.OAuthFlows)) {
      return super.equals(obj);
    }
    org.mojolang.mojo.openapi.OAuthFlows other = (org.mojolang.mojo.openapi.OAuthFlows) obj;

    if (hasImplicit() != other.hasImplicit()) return false;
    if (hasImplicit()) {
      if (!getImplicit()
          .equals(other.getImplicit())) return false;
    }
    if (hasPassword() != other.hasPassword()) return false;
    if (hasPassword()) {
      if (!getPassword()
          .equals(other.getPassword())) return false;
    }
    if (hasClientCredentials() != other.hasClientCredentials()) return false;
    if (hasClientCredentials()) {
      if (!getClientCredentials()
          .equals(other.getClientCredentials())) return false;
    }
    if (hasAuthorizationCode() != other.hasAuthorizationCode()) return false;
    if (hasAuthorizationCode()) {
      if (!getAuthorizationCode()
          .equals(other.getAuthorizationCode())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasImplicit()) {
      hash = (37 * hash) + IMPLICIT_FIELD_NUMBER;
      hash = (53 * hash) + getImplicit().hashCode();
    }
    if (hasPassword()) {
      hash = (37 * hash) + PASSWORD_FIELD_NUMBER;
      hash = (53 * hash) + getPassword().hashCode();
    }
    if (hasClientCredentials()) {
      hash = (37 * hash) + CLIENT_CREDENTIALS_FIELD_NUMBER;
      hash = (53 * hash) + getClientCredentials().hashCode();
    }
    if (hasAuthorizationCode()) {
      hash = (37 * hash) + AUTHORIZATION_CODE_FIELD_NUMBER;
      hash = (53 * hash) + getAuthorizationCode().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.mojolang.mojo.openapi.OAuthFlows parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.mojolang.mojo.openapi.OAuthFlows parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.mojolang.mojo.openapi.OAuthFlows parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.mojolang.mojo.openapi.OAuthFlows parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.mojolang.mojo.openapi.OAuthFlows parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.mojolang.mojo.openapi.OAuthFlows parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.mojolang.mojo.openapi.OAuthFlows parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.mojolang.mojo.openapi.OAuthFlows parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.mojolang.mojo.openapi.OAuthFlows parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.mojolang.mojo.openapi.OAuthFlows parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.mojolang.mojo.openapi.OAuthFlows parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.mojolang.mojo.openapi.OAuthFlows parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.mojolang.mojo.openapi.OAuthFlows prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code mojo.openapi.OAuthFlows}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:mojo.openapi.OAuthFlows)
      org.mojolang.mojo.openapi.OAuthFlowsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.mojolang.mojo.openapi.OauthFlowsProto.internal_static_mojo_openapi_OAuthFlows_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.mojolang.mojo.openapi.OauthFlowsProto.internal_static_mojo_openapi_OAuthFlows_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.mojolang.mojo.openapi.OAuthFlows.class, org.mojolang.mojo.openapi.OAuthFlows.Builder.class);
    }

    // Construct using org.mojolang.mojo.openapi.OAuthFlows.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (implicitBuilder_ == null) {
        implicit_ = null;
      } else {
        implicit_ = null;
        implicitBuilder_ = null;
      }
      if (passwordBuilder_ == null) {
        password_ = null;
      } else {
        password_ = null;
        passwordBuilder_ = null;
      }
      if (clientCredentialsBuilder_ == null) {
        clientCredentials_ = null;
      } else {
        clientCredentials_ = null;
        clientCredentialsBuilder_ = null;
      }
      if (authorizationCodeBuilder_ == null) {
        authorizationCode_ = null;
      } else {
        authorizationCode_ = null;
        authorizationCodeBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.mojolang.mojo.openapi.OauthFlowsProto.internal_static_mojo_openapi_OAuthFlows_descriptor;
    }

    @java.lang.Override
    public org.mojolang.mojo.openapi.OAuthFlows getDefaultInstanceForType() {
      return org.mojolang.mojo.openapi.OAuthFlows.getDefaultInstance();
    }

    @java.lang.Override
    public org.mojolang.mojo.openapi.OAuthFlows build() {
      org.mojolang.mojo.openapi.OAuthFlows result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.mojolang.mojo.openapi.OAuthFlows buildPartial() {
      org.mojolang.mojo.openapi.OAuthFlows result = new org.mojolang.mojo.openapi.OAuthFlows(this);
      if (implicitBuilder_ == null) {
        result.implicit_ = implicit_;
      } else {
        result.implicit_ = implicitBuilder_.build();
      }
      if (passwordBuilder_ == null) {
        result.password_ = password_;
      } else {
        result.password_ = passwordBuilder_.build();
      }
      if (clientCredentialsBuilder_ == null) {
        result.clientCredentials_ = clientCredentials_;
      } else {
        result.clientCredentials_ = clientCredentialsBuilder_.build();
      }
      if (authorizationCodeBuilder_ == null) {
        result.authorizationCode_ = authorizationCode_;
      } else {
        result.authorizationCode_ = authorizationCodeBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.mojolang.mojo.openapi.OAuthFlows) {
        return mergeFrom((org.mojolang.mojo.openapi.OAuthFlows)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.mojolang.mojo.openapi.OAuthFlows other) {
      if (other == org.mojolang.mojo.openapi.OAuthFlows.getDefaultInstance()) return this;
      if (other.hasImplicit()) {
        mergeImplicit(other.getImplicit());
      }
      if (other.hasPassword()) {
        mergePassword(other.getPassword());
      }
      if (other.hasClientCredentials()) {
        mergeClientCredentials(other.getClientCredentials());
      }
      if (other.hasAuthorizationCode()) {
        mergeAuthorizationCode(other.getAuthorizationCode());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.mojolang.mojo.openapi.OAuthFlows parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.mojolang.mojo.openapi.OAuthFlows) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private org.mojolang.mojo.openapi.OAuthFlow implicit_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.mojolang.mojo.openapi.OAuthFlow, org.mojolang.mojo.openapi.OAuthFlow.Builder, org.mojolang.mojo.openapi.OAuthFlowOrBuilder> implicitBuilder_;
    /**
     * <code>.mojo.openapi.OAuthFlow implicit = 1;</code>
     * @return Whether the implicit field is set.
     */
    public boolean hasImplicit() {
      return implicitBuilder_ != null || implicit_ != null;
    }
    /**
     * <code>.mojo.openapi.OAuthFlow implicit = 1;</code>
     * @return The implicit.
     */
    public org.mojolang.mojo.openapi.OAuthFlow getImplicit() {
      if (implicitBuilder_ == null) {
        return implicit_ == null ? org.mojolang.mojo.openapi.OAuthFlow.getDefaultInstance() : implicit_;
      } else {
        return implicitBuilder_.getMessage();
      }
    }
    /**
     * <code>.mojo.openapi.OAuthFlow implicit = 1;</code>
     */
    public Builder setImplicit(org.mojolang.mojo.openapi.OAuthFlow value) {
      if (implicitBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        implicit_ = value;
        onChanged();
      } else {
        implicitBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.mojo.openapi.OAuthFlow implicit = 1;</code>
     */
    public Builder setImplicit(
        org.mojolang.mojo.openapi.OAuthFlow.Builder builderForValue) {
      if (implicitBuilder_ == null) {
        implicit_ = builderForValue.build();
        onChanged();
      } else {
        implicitBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.mojo.openapi.OAuthFlow implicit = 1;</code>
     */
    public Builder mergeImplicit(org.mojolang.mojo.openapi.OAuthFlow value) {
      if (implicitBuilder_ == null) {
        if (implicit_ != null) {
          implicit_ =
            org.mojolang.mojo.openapi.OAuthFlow.newBuilder(implicit_).mergeFrom(value).buildPartial();
        } else {
          implicit_ = value;
        }
        onChanged();
      } else {
        implicitBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.mojo.openapi.OAuthFlow implicit = 1;</code>
     */
    public Builder clearImplicit() {
      if (implicitBuilder_ == null) {
        implicit_ = null;
        onChanged();
      } else {
        implicit_ = null;
        implicitBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.mojo.openapi.OAuthFlow implicit = 1;</code>
     */
    public org.mojolang.mojo.openapi.OAuthFlow.Builder getImplicitBuilder() {
      
      onChanged();
      return getImplicitFieldBuilder().getBuilder();
    }
    /**
     * <code>.mojo.openapi.OAuthFlow implicit = 1;</code>
     */
    public org.mojolang.mojo.openapi.OAuthFlowOrBuilder getImplicitOrBuilder() {
      if (implicitBuilder_ != null) {
        return implicitBuilder_.getMessageOrBuilder();
      } else {
        return implicit_ == null ?
            org.mojolang.mojo.openapi.OAuthFlow.getDefaultInstance() : implicit_;
      }
    }
    /**
     * <code>.mojo.openapi.OAuthFlow implicit = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.mojolang.mojo.openapi.OAuthFlow, org.mojolang.mojo.openapi.OAuthFlow.Builder, org.mojolang.mojo.openapi.OAuthFlowOrBuilder> 
        getImplicitFieldBuilder() {
      if (implicitBuilder_ == null) {
        implicitBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.mojolang.mojo.openapi.OAuthFlow, org.mojolang.mojo.openapi.OAuthFlow.Builder, org.mojolang.mojo.openapi.OAuthFlowOrBuilder>(
                getImplicit(),
                getParentForChildren(),
                isClean());
        implicit_ = null;
      }
      return implicitBuilder_;
    }

    private org.mojolang.mojo.openapi.OAuthFlow password_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.mojolang.mojo.openapi.OAuthFlow, org.mojolang.mojo.openapi.OAuthFlow.Builder, org.mojolang.mojo.openapi.OAuthFlowOrBuilder> passwordBuilder_;
    /**
     * <code>.mojo.openapi.OAuthFlow password = 2;</code>
     * @return Whether the password field is set.
     */
    public boolean hasPassword() {
      return passwordBuilder_ != null || password_ != null;
    }
    /**
     * <code>.mojo.openapi.OAuthFlow password = 2;</code>
     * @return The password.
     */
    public org.mojolang.mojo.openapi.OAuthFlow getPassword() {
      if (passwordBuilder_ == null) {
        return password_ == null ? org.mojolang.mojo.openapi.OAuthFlow.getDefaultInstance() : password_;
      } else {
        return passwordBuilder_.getMessage();
      }
    }
    /**
     * <code>.mojo.openapi.OAuthFlow password = 2;</code>
     */
    public Builder setPassword(org.mojolang.mojo.openapi.OAuthFlow value) {
      if (passwordBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        password_ = value;
        onChanged();
      } else {
        passwordBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.mojo.openapi.OAuthFlow password = 2;</code>
     */
    public Builder setPassword(
        org.mojolang.mojo.openapi.OAuthFlow.Builder builderForValue) {
      if (passwordBuilder_ == null) {
        password_ = builderForValue.build();
        onChanged();
      } else {
        passwordBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.mojo.openapi.OAuthFlow password = 2;</code>
     */
    public Builder mergePassword(org.mojolang.mojo.openapi.OAuthFlow value) {
      if (passwordBuilder_ == null) {
        if (password_ != null) {
          password_ =
            org.mojolang.mojo.openapi.OAuthFlow.newBuilder(password_).mergeFrom(value).buildPartial();
        } else {
          password_ = value;
        }
        onChanged();
      } else {
        passwordBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.mojo.openapi.OAuthFlow password = 2;</code>
     */
    public Builder clearPassword() {
      if (passwordBuilder_ == null) {
        password_ = null;
        onChanged();
      } else {
        password_ = null;
        passwordBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.mojo.openapi.OAuthFlow password = 2;</code>
     */
    public org.mojolang.mojo.openapi.OAuthFlow.Builder getPasswordBuilder() {
      
      onChanged();
      return getPasswordFieldBuilder().getBuilder();
    }
    /**
     * <code>.mojo.openapi.OAuthFlow password = 2;</code>
     */
    public org.mojolang.mojo.openapi.OAuthFlowOrBuilder getPasswordOrBuilder() {
      if (passwordBuilder_ != null) {
        return passwordBuilder_.getMessageOrBuilder();
      } else {
        return password_ == null ?
            org.mojolang.mojo.openapi.OAuthFlow.getDefaultInstance() : password_;
      }
    }
    /**
     * <code>.mojo.openapi.OAuthFlow password = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.mojolang.mojo.openapi.OAuthFlow, org.mojolang.mojo.openapi.OAuthFlow.Builder, org.mojolang.mojo.openapi.OAuthFlowOrBuilder> 
        getPasswordFieldBuilder() {
      if (passwordBuilder_ == null) {
        passwordBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.mojolang.mojo.openapi.OAuthFlow, org.mojolang.mojo.openapi.OAuthFlow.Builder, org.mojolang.mojo.openapi.OAuthFlowOrBuilder>(
                getPassword(),
                getParentForChildren(),
                isClean());
        password_ = null;
      }
      return passwordBuilder_;
    }

    private org.mojolang.mojo.openapi.OAuthFlow clientCredentials_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.mojolang.mojo.openapi.OAuthFlow, org.mojolang.mojo.openapi.OAuthFlow.Builder, org.mojolang.mojo.openapi.OAuthFlowOrBuilder> clientCredentialsBuilder_;
    /**
     * <code>.mojo.openapi.OAuthFlow client_credentials = 3;</code>
     * @return Whether the clientCredentials field is set.
     */
    public boolean hasClientCredentials() {
      return clientCredentialsBuilder_ != null || clientCredentials_ != null;
    }
    /**
     * <code>.mojo.openapi.OAuthFlow client_credentials = 3;</code>
     * @return The clientCredentials.
     */
    public org.mojolang.mojo.openapi.OAuthFlow getClientCredentials() {
      if (clientCredentialsBuilder_ == null) {
        return clientCredentials_ == null ? org.mojolang.mojo.openapi.OAuthFlow.getDefaultInstance() : clientCredentials_;
      } else {
        return clientCredentialsBuilder_.getMessage();
      }
    }
    /**
     * <code>.mojo.openapi.OAuthFlow client_credentials = 3;</code>
     */
    public Builder setClientCredentials(org.mojolang.mojo.openapi.OAuthFlow value) {
      if (clientCredentialsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        clientCredentials_ = value;
        onChanged();
      } else {
        clientCredentialsBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.mojo.openapi.OAuthFlow client_credentials = 3;</code>
     */
    public Builder setClientCredentials(
        org.mojolang.mojo.openapi.OAuthFlow.Builder builderForValue) {
      if (clientCredentialsBuilder_ == null) {
        clientCredentials_ = builderForValue.build();
        onChanged();
      } else {
        clientCredentialsBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.mojo.openapi.OAuthFlow client_credentials = 3;</code>
     */
    public Builder mergeClientCredentials(org.mojolang.mojo.openapi.OAuthFlow value) {
      if (clientCredentialsBuilder_ == null) {
        if (clientCredentials_ != null) {
          clientCredentials_ =
            org.mojolang.mojo.openapi.OAuthFlow.newBuilder(clientCredentials_).mergeFrom(value).buildPartial();
        } else {
          clientCredentials_ = value;
        }
        onChanged();
      } else {
        clientCredentialsBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.mojo.openapi.OAuthFlow client_credentials = 3;</code>
     */
    public Builder clearClientCredentials() {
      if (clientCredentialsBuilder_ == null) {
        clientCredentials_ = null;
        onChanged();
      } else {
        clientCredentials_ = null;
        clientCredentialsBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.mojo.openapi.OAuthFlow client_credentials = 3;</code>
     */
    public org.mojolang.mojo.openapi.OAuthFlow.Builder getClientCredentialsBuilder() {
      
      onChanged();
      return getClientCredentialsFieldBuilder().getBuilder();
    }
    /**
     * <code>.mojo.openapi.OAuthFlow client_credentials = 3;</code>
     */
    public org.mojolang.mojo.openapi.OAuthFlowOrBuilder getClientCredentialsOrBuilder() {
      if (clientCredentialsBuilder_ != null) {
        return clientCredentialsBuilder_.getMessageOrBuilder();
      } else {
        return clientCredentials_ == null ?
            org.mojolang.mojo.openapi.OAuthFlow.getDefaultInstance() : clientCredentials_;
      }
    }
    /**
     * <code>.mojo.openapi.OAuthFlow client_credentials = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.mojolang.mojo.openapi.OAuthFlow, org.mojolang.mojo.openapi.OAuthFlow.Builder, org.mojolang.mojo.openapi.OAuthFlowOrBuilder> 
        getClientCredentialsFieldBuilder() {
      if (clientCredentialsBuilder_ == null) {
        clientCredentialsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.mojolang.mojo.openapi.OAuthFlow, org.mojolang.mojo.openapi.OAuthFlow.Builder, org.mojolang.mojo.openapi.OAuthFlowOrBuilder>(
                getClientCredentials(),
                getParentForChildren(),
                isClean());
        clientCredentials_ = null;
      }
      return clientCredentialsBuilder_;
    }

    private org.mojolang.mojo.openapi.OAuthFlow authorizationCode_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.mojolang.mojo.openapi.OAuthFlow, org.mojolang.mojo.openapi.OAuthFlow.Builder, org.mojolang.mojo.openapi.OAuthFlowOrBuilder> authorizationCodeBuilder_;
    /**
     * <code>.mojo.openapi.OAuthFlow authorization_code = 4;</code>
     * @return Whether the authorizationCode field is set.
     */
    public boolean hasAuthorizationCode() {
      return authorizationCodeBuilder_ != null || authorizationCode_ != null;
    }
    /**
     * <code>.mojo.openapi.OAuthFlow authorization_code = 4;</code>
     * @return The authorizationCode.
     */
    public org.mojolang.mojo.openapi.OAuthFlow getAuthorizationCode() {
      if (authorizationCodeBuilder_ == null) {
        return authorizationCode_ == null ? org.mojolang.mojo.openapi.OAuthFlow.getDefaultInstance() : authorizationCode_;
      } else {
        return authorizationCodeBuilder_.getMessage();
      }
    }
    /**
     * <code>.mojo.openapi.OAuthFlow authorization_code = 4;</code>
     */
    public Builder setAuthorizationCode(org.mojolang.mojo.openapi.OAuthFlow value) {
      if (authorizationCodeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        authorizationCode_ = value;
        onChanged();
      } else {
        authorizationCodeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.mojo.openapi.OAuthFlow authorization_code = 4;</code>
     */
    public Builder setAuthorizationCode(
        org.mojolang.mojo.openapi.OAuthFlow.Builder builderForValue) {
      if (authorizationCodeBuilder_ == null) {
        authorizationCode_ = builderForValue.build();
        onChanged();
      } else {
        authorizationCodeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.mojo.openapi.OAuthFlow authorization_code = 4;</code>
     */
    public Builder mergeAuthorizationCode(org.mojolang.mojo.openapi.OAuthFlow value) {
      if (authorizationCodeBuilder_ == null) {
        if (authorizationCode_ != null) {
          authorizationCode_ =
            org.mojolang.mojo.openapi.OAuthFlow.newBuilder(authorizationCode_).mergeFrom(value).buildPartial();
        } else {
          authorizationCode_ = value;
        }
        onChanged();
      } else {
        authorizationCodeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.mojo.openapi.OAuthFlow authorization_code = 4;</code>
     */
    public Builder clearAuthorizationCode() {
      if (authorizationCodeBuilder_ == null) {
        authorizationCode_ = null;
        onChanged();
      } else {
        authorizationCode_ = null;
        authorizationCodeBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.mojo.openapi.OAuthFlow authorization_code = 4;</code>
     */
    public org.mojolang.mojo.openapi.OAuthFlow.Builder getAuthorizationCodeBuilder() {
      
      onChanged();
      return getAuthorizationCodeFieldBuilder().getBuilder();
    }
    /**
     * <code>.mojo.openapi.OAuthFlow authorization_code = 4;</code>
     */
    public org.mojolang.mojo.openapi.OAuthFlowOrBuilder getAuthorizationCodeOrBuilder() {
      if (authorizationCodeBuilder_ != null) {
        return authorizationCodeBuilder_.getMessageOrBuilder();
      } else {
        return authorizationCode_ == null ?
            org.mojolang.mojo.openapi.OAuthFlow.getDefaultInstance() : authorizationCode_;
      }
    }
    /**
     * <code>.mojo.openapi.OAuthFlow authorization_code = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.mojolang.mojo.openapi.OAuthFlow, org.mojolang.mojo.openapi.OAuthFlow.Builder, org.mojolang.mojo.openapi.OAuthFlowOrBuilder> 
        getAuthorizationCodeFieldBuilder() {
      if (authorizationCodeBuilder_ == null) {
        authorizationCodeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.mojolang.mojo.openapi.OAuthFlow, org.mojolang.mojo.openapi.OAuthFlow.Builder, org.mojolang.mojo.openapi.OAuthFlowOrBuilder>(
                getAuthorizationCode(),
                getParentForChildren(),
                isClean());
        authorizationCode_ = null;
      }
      return authorizationCodeBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:mojo.openapi.OAuthFlows)
  }

  // @@protoc_insertion_point(class_scope:mojo.openapi.OAuthFlows)
  private static final org.mojolang.mojo.openapi.OAuthFlows DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.mojolang.mojo.openapi.OAuthFlows();
  }

  public static org.mojolang.mojo.openapi.OAuthFlows getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<OAuthFlows>
      PARSER = new com.google.protobuf.AbstractParser<OAuthFlows>() {
    @java.lang.Override
    public OAuthFlows parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new OAuthFlows(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<OAuthFlows> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<OAuthFlows> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.mojolang.mojo.openapi.OAuthFlows getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

