// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/openapi/openapi.proto

package org.mojolang.mojo.openapi;

public final class OpenapiProto {
  private OpenapiProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_openapi_Components_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_openapi_Components_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_openapi_Components_SchemasEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_openapi_Components_SchemasEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_openapi_Components_ResponsesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_openapi_Components_ResponsesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_openapi_Components_ParametersEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_openapi_Components_ParametersEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_openapi_Components_ExamplesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_openapi_Components_ExamplesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_openapi_Components_RequestBodiesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_openapi_Components_RequestBodiesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_openapi_Components_HeadersEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_openapi_Components_HeadersEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_openapi_Components_SecuritySchemesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_openapi_Components_SecuritySchemesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_openapi_Components_LinksEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_openapi_Components_LinksEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_openapi_Components_CallbacksEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_openapi_Components_CallbacksEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_openapi_Components_PathItemsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_openapi_Components_PathItemsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_openapi_OpenAPI_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_openapi_OpenAPI_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_openapi_Callback_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_openapi_Callback_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_openapi_Callback_ValuesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_openapi_Callback_ValuesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_openapi_Encoding_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_openapi_Encoding_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_openapi_Encoding_HeadersEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_openapi_Encoding_HeadersEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_openapi_Header_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_openapi_Header_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_openapi_Header_ExamplesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_openapi_Header_ExamplesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_openapi_Header_ContentEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_openapi_Header_ContentEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_openapi_MediaType_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_openapi_MediaType_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_openapi_MediaType_ExamplesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_openapi_MediaType_ExamplesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_openapi_MediaType_EncodingEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_openapi_MediaType_EncodingEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_openapi_Operation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_openapi_Operation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_openapi_Operation_CallbacksEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_openapi_Operation_CallbacksEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_openapi_Parameter_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_openapi_Parameter_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_openapi_Parameter_ExamplesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_openapi_Parameter_ExamplesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_openapi_Parameter_ContentEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_openapi_Parameter_ContentEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_openapi_PathItem_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_openapi_PathItem_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_openapi_RequestBody_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_openapi_RequestBody_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_openapi_RequestBody_ContentEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_openapi_RequestBody_ContentEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_openapi_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_openapi_Response_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_openapi_Response_HeadersEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_openapi_Response_HeadersEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_openapi_Response_ContentEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_openapi_Response_ContentEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_openapi_Response_LinksEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_openapi_Response_LinksEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_openapi_Responses_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_openapi_Responses_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_openapi_Responses_ValuesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_openapi_Responses_ValuesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_openapi_Schema_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_openapi_Schema_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_openapi_Schema_PropertiesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_openapi_Schema_PropertiesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_openapi_ReferenceableResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_openapi_ReferenceableResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_openapi_ReferenceableParameter_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_openapi_ReferenceableParameter_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_openapi_ReferenceableRequestBody_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_openapi_ReferenceableRequestBody_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_openapi_ReferenceableHeader_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_openapi_ReferenceableHeader_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_openapi_ReferenceableCallback_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_openapi_ReferenceableCallback_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_openapi_ReferenceableSchema_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_openapi_ReferenceableSchema_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_openapi_Paths_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_openapi_Paths_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_openapi_Paths_ValuesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_openapi_Paths_ValuesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_openapi_ReferenceablePathItem_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_openapi_ReferenceablePathItem_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032mojo/openapi/openapi.proto\022\014mojo.opena" +
      "pi\032\023mojo/core/any.proto\032\025mojo/core/regex" +
      ".proto\032\025mojo/core/value.proto\032\027mojo/core" +
      "/version.proto\032\017mojo/mojo.proto\032\"mojo/op" +
      "enapi/cached_document.proto\032 mojo/openap" +
      "i/discriminator.proto\032$mojo/openapi/exte" +
      "rnal_document.proto\032\027mojo/openapi/info.p" +
      "roto\032\034mojo/openapi/reference.proto\032(mojo" +
      "/openapi/referenceable_example.proto\032%mo" +
      "jo/openapi/referenceable_link.proto\0320moj" +
      "o/openapi/referenceable_security_scheme." +
      "proto\032\'mojo/openapi/security_requirement" +
      ".proto\032\031mojo/openapi/server.proto\032\026mojo/" +
      "openapi/tag.proto\032\026mojo/openapi/xml.prot" +
      "o\"\307\013\n\nComponents\0226\n\007schemas\030\001 \003(\0132%.mojo" +
      ".openapi.Components.SchemasEntry\022:\n\tresp" +
      "onses\030\002 \003(\0132\'.mojo.openapi.Components.Re" +
      "sponsesEntry\022<\n\nparameters\030\003 \003(\0132(.mojo." +
      "openapi.Components.ParametersEntry\0228\n\010ex" +
      "amples\030\004 \003(\0132&.mojo.openapi.Components.E" +
      "xamplesEntry\022C\n\016request_bodies\030\005 \003(\0132+.m" +
      "ojo.openapi.Components.RequestBodiesEntr" +
      "y\0226\n\007headers\030\006 \003(\0132%.mojo.openapi.Compon" +
      "ents.HeadersEntry\022G\n\020security_schemes\030\007 " +
      "\003(\0132-.mojo.openapi.Components.SecuritySc" +
      "hemesEntry\0222\n\005links\030\010 \003(\0132#.mojo.openapi" +
      ".Components.LinksEntry\022:\n\tcallbacks\030\t \003(" +
      "\0132\'.mojo.openapi.Components.CallbacksEnt" +
      "ry\022;\n\npath_items\030\n \003(\0132\'.mojo.openapi.Co" +
      "mponents.PathItemsEntry\032D\n\014SchemasEntry\022" +
      "\013\n\003key\030\001 \001(\t\022#\n\005value\030\002 \001(\0132\024.mojo.opena" +
      "pi.Schema:\0028\001\032U\n\016ResponsesEntry\022\013\n\003key\030\001" +
      " \001(\t\0222\n\005value\030\002 \001(\0132#.mojo.openapi.Refer" +
      "enceableResponse:\0028\001\032W\n\017ParametersEntry\022" +
      "\013\n\003key\030\001 \001(\t\0223\n\005value\030\002 \001(\0132$.mojo.opena" +
      "pi.ReferenceableParameter:\0028\001\032S\n\rExample" +
      "sEntry\022\013\n\003key\030\001 \001(\t\0221\n\005value\030\002 \001(\0132\".moj" +
      "o.openapi.ReferenceableExample:\0028\001\032\\\n\022Re" +
      "questBodiesEntry\022\013\n\003key\030\001 \001(\t\0225\n\005value\030\002" +
      " \001(\0132&.mojo.openapi.ReferenceableRequest" +
      "Body:\0028\001\032Q\n\014HeadersEntry\022\013\n\003key\030\001 \001(\t\0220\n" +
      "\005value\030\002 \001(\0132!.mojo.openapi.Referenceabl" +
      "eHeader:\0028\001\032a\n\024SecuritySchemesEntry\022\013\n\003k" +
      "ey\030\001 \001(\t\0228\n\005value\030\002 \001(\0132).mojo.openapi.R" +
      "eferenceableSecurityScheme:\0028\001\032M\n\nLinksE" +
      "ntry\022\013\n\003key\030\001 \001(\t\022.\n\005value\030\002 \001(\0132\037.mojo." +
      "openapi.ReferenceableLink:\0028\001\032U\n\016Callbac" +
      "ksEntry\022\013\n\003key\030\001 \001(\t\0222\n\005value\030\002 \001(\0132#.mo" +
      "jo.openapi.ReferenceableCallback:\0028\001\032U\n\016" +
      "PathItemsEntry\022\013\n\003key\030\001 \001(\t\0222\n\005value\030\002 \001" +
      "(\0132#.mojo.openapi.ReferenceablePathItem:" +
      "\0028\001\"\326\002\n\007OpenAPI\022#\n\007openapi\030\001 \001(\0132\022.mojo." +
      "core.Version\022 \n\004info\030\002 \001(\0132\022.mojo.openap" +
      "i.Info\022%\n\007servers\030\004 \003(\0132\024.mojo.openapi.S" +
      "erver\022\"\n\005paths\030\005 \001(\0132\023.mojo.openapi.Path" +
      "s\022,\n\ncomponents\030\n \001(\0132\030.mojo.openapi.Com" +
      "ponents\0223\n\010security\030\013 \001(\0132!.mojo.openapi" +
      ".SecurityRequirement\022\037\n\004tags\030\014 \003(\0132\021.moj" +
      "o.openapi.Tag\0225\n\rexternal_docs\030\r \001(\0132\036.m" +
      "ojo.openapi.ExternalDocument\"\205\001\n\010Callbac" +
      "k\0222\n\006values\030\001 \003(\0132\".mojo.openapi.Callbac" +
      "k.ValuesEntry\032E\n\013ValuesEntry\022\013\n\003key\030\001 \001(" +
      "\t\022%\n\005value\030\002 \001(\0132\026.mojo.openapi.PathItem" +
      ":\0028\001\"\341\001\n\010Encoding\022\024\n\014content_type\030\001 \001(\t\022" +
      "4\n\007headers\030\002 \003(\0132#.mojo.openapi.Encoding" +
      ".HeadersEntry\022\r\n\005style\030\003 \001(\t\022\017\n\007explode\030" +
      "\004 \001(\010\022\026\n\016allow_reserved\030\005 \001(\010\032Q\n\014Headers" +
      "Entry\022\013\n\003key\030\001 \001(\t\0220\n\005value\030\002 \001(\0132!.mojo" +
      ".openapi.ReferenceableHeader:\0028\001\"\315\004\n\006Hea" +
      "der\022\014\n\004name\030\001 \001(\t\022,\n\002in\030\002 \001(\0162 .mojo.ope" +
      "napi.Parameter.Location\022\023\n\013description\030\003" +
      " \001(\t\022\020\n\010required\030\004 \001(\010\022\022\n\ndeprecated\030\005 \001" +
      "(\010\022\031\n\021allow_empty_value\030\006 \001(\010\022,\n\005style\030\n" +
      " \001(\0162\035.mojo.openapi.Parameter.Style\022\017\n\007e" +
      "xplode\030\013 \001(\010\022\026\n\016allow_reserved\030\014 \001(\010\0221\n\006" +
      "schema\030\r \001(\0132!.mojo.openapi.Referenceabl" +
      "eSchema\022\037\n\007example\030\016 \001(\0132\016.mojo.core.Any" +
      "\0224\n\010examples\030\017 \003(\0132\".mojo.openapi.Header" +
      ".ExamplesEntry\0222\n\007content\030\024 \003(\0132!.mojo.o" +
      "penapi.Header.ContentEntry\032S\n\rExamplesEn" +
      "try\022\013\n\003key\030\001 \001(\t\0221\n\005value\030\002 \001(\0132\".mojo.o" +
      "penapi.ReferenceableExample:\0028\001\032G\n\014Conte" +
      "ntEntry\022\013\n\003key\030\001 \001(\t\022&\n\005value\030\002 \001(\0132\027.mo" +
      "jo.openapi.MediaType:\0028\001\"\357\002\n\tMediaType\0221" +
      "\n\006schema\030\001 \001(\0132!.mojo.openapi.Referencea" +
      "bleSchema\022\037\n\007example\030\002 \001(\0132\016.mojo.core.A" +
      "ny\0227\n\010examples\030\003 \003(\0132%.mojo.openapi.Medi" +
      "aType.ExamplesEntry\0227\n\010encoding\030\005 \003(\0132%." +
      "mojo.openapi.MediaType.EncodingEntry\032S\n\r" +
      "ExamplesEntry\022\013\n\003key\030\001 \001(\t\0221\n\005value\030\002 \001(" +
      "\0132\".mojo.openapi.ReferenceableExample:\0028" +
      "\001\032G\n\rEncodingEntry\022\013\n\003key\030\001 \001(\t\022%\n\005value" +
      "\030\002 \001(\0132\026.mojo.openapi.Encoding:\0028\001\"\320\004\n\tO" +
      "peration\022\014\n\004tags\030\001 \003(\t\022\017\n\007summary\030\002 \001(\t\022" +
      "1\n\013description\030\003 \001(\0132\034.mojo.openapi.Cach" +
      "edDocument\0225\n\rexternal_docs\030\004 \001(\0132\036.mojo" +
      ".openapi.ExternalDocument\022\024\n\014operation_i" +
      "d\030\005 \001(\t\0228\n\nparameters\030\n \003(\0132$.mojo.opena" +
      "pi.ReferenceableParameter\022<\n\014request_bod" +
      "y\030\013 \001(\0132&.mojo.openapi.ReferenceableRequ" +
      "estBody\022*\n\tresponses\030\014 \001(\0132\027.mojo.openap" +
      "i.Responses\0229\n\tcallbacks\030\r \003(\0132&.mojo.op" +
      "enapi.Operation.CallbacksEntry\022\022\n\ndeprec" +
      "ated\030\017 \001(\010\0223\n\010security\030\020 \001(\0132!.mojo.open" +
      "api.SecurityRequirement\022%\n\007servers\030\021 \003(\013" +
      "2\024.mojo.openapi.Server\032U\n\016CallbacksEntry" +
      "\022\013\n\003key\030\001 \001(\t\0222\n\005value\030\002 \001(\0132#.mojo.open" +
      "api.ReferenceableCallback:\0028\001\"\377\006\n\tParame" +
      "ter\022\014\n\004name\030\001 \001(\t\022,\n\002in\030\002 \001(\0162 .mojo.ope" +
      "napi.Parameter.Location\022\023\n\013description\030\003" +
      " \001(\t\022\020\n\010required\030\004 \001(\010\022\022\n\ndeprecated\030\005 \001" +
      "(\010\022\031\n\021allow_empty_value\030\006 \001(\010\022,\n\005style\030\n" +
      " \001(\0162\035.mojo.openapi.Parameter.Style\022\017\n\007e" +
      "xplode\030\013 \001(\010\022\026\n\016allow_reserved\030\014 \001(\010\0221\n\006" +
      "schema\030\r \001(\0132!.mojo.openapi.Referenceabl" +
      "eSchema\022\037\n\007example\030\016 \001(\0132\016.mojo.core.Any" +
      "\0227\n\010examples\030\017 \003(\0132%.mojo.openapi.Parame" +
      "ter.ExamplesEntry\0225\n\007content\030\024 \003(\0132$.moj" +
      "o.openapi.Parameter.ContentEntry\032S\n\rExam" +
      "plesEntry\022\013\n\003key\030\001 \001(\t\0221\n\005value\030\002 \001(\0132\"." +
      "mojo.openapi.ReferenceableExample:\0028\001\032G\n" +
      "\014ContentEntry\022\013\n\003key\030\001 \001(\t\022&\n\005value\030\002 \001(" +
      "\0132\027.mojo.openapi.MediaType:\0028\001\"u\n\010Locati" +
      "on\022\030\n\024LOCATION_UNSPECIFIED\020\000\022\021\n\rLOCATION" +
      "_PATH\020\001\022\022\n\016LOCATION_QUERY\020\002\022\023\n\017LOCATION_" +
      "HEADER\020\003\022\023\n\017LOCATION_COOKIE\020\004\"\257\001\n\005Style\022" +
      "\025\n\021STYLE_UNSPECIFIED\020\000\022\020\n\014STYLE_MATRIX\020\001" +
      "\022\017\n\013STYLE_LABEL\020\002\022\016\n\nSTYLE_FORM\020\003\022\020\n\014STY" +
      "LE_SIMPLE\020\004\022\031\n\025STYLE_SPACE_DELIMITED\020\005\022\030" +
      "\n\024STYLE_PIPE_DELIMITED\020\006\022\025\n\021STYLE_DEEP_O" +
      "BJECT\020\007\"\203\004\n\010PathItem\022\025\n\003ref\030\001 \001(\tB\010\312\317$\004$" +
      "ref\022\017\n\007summary\030\002 \001(\t\0221\n\013description\030\003 \001(" +
      "\0132\034.mojo.openapi.CachedDocument\022$\n\003get\030\005" +
      " \001(\0132\027.mojo.openapi.Operation\022$\n\003put\030\006 \001" +
      "(\0132\027.mojo.openapi.Operation\022%\n\004post\030\007 \001(" +
      "\0132\027.mojo.openapi.Operation\022\'\n\006delete\030\010 \001" +
      "(\0132\027.mojo.openapi.Operation\022(\n\007options\030\t" +
      " \001(\0132\027.mojo.openapi.Operation\022%\n\004head\030\n " +
      "\001(\0132\027.mojo.openapi.Operation\022&\n\005patch\030\013 " +
      "\001(\0132\027.mojo.openapi.Operation\022&\n\005trace\030\014 " +
      "\001(\0132\027.mojo.openapi.Operation\022%\n\007servers\030" +
      "\r \003(\0132\024.mojo.openapi.Server\0228\n\nparameter" +
      "s\030\017 \003(\0132$.mojo.openapi.ReferenceablePara" +
      "meter\"\324\001\n\013RequestBody\0221\n\013description\030\001 \001" +
      "(\0132\034.mojo.openapi.CachedDocument\0227\n\007cont" +
      "ent\030\002 \003(\0132&.mojo.openapi.RequestBody.Con" +
      "tentEntry\022\020\n\010required\030\003 \001(\010\032G\n\014ContentEn" +
      "try\022\013\n\003key\030\001 \001(\t\022&\n\005value\030\002 \001(\0132\027.mojo.o" +
      "penapi.MediaType:\0028\001\"\250\003\n\010Response\022\023\n\013des" +
      "cription\030\001 \001(\t\0224\n\007headers\030\002 \003(\0132#.mojo.o" +
      "penapi.Response.HeadersEntry\0224\n\007content\030" +
      "\003 \003(\0132#.mojo.openapi.Response.ContentEnt" +
      "ry\0220\n\005links\030\004 \003(\0132!.mojo.openapi.Respons" +
      "e.LinksEntry\032Q\n\014HeadersEntry\022\013\n\003key\030\001 \001(" +
      "\t\0220\n\005value\030\002 \001(\0132!.mojo.openapi.Referenc" +
      "eableHeader:\0028\001\032G\n\014ContentEntry\022\013\n\003key\030\001" +
      " \001(\t\022&\n\005value\030\002 \001(\0132\027.mojo.openapi.Media" +
      "Type:\0028\001\032M\n\nLinksEntry\022\013\n\003key\030\001 \001(\t\022.\n\005v" +
      "alue\030\002 \001(\0132\037.mojo.openapi.ReferenceableL" +
      "ink:\0028\001\"\224\001\n\tResponses\0223\n\006values\030\001 \003(\0132#." +
      "mojo.openapi.Responses.ValuesEntry\032R\n\013Va" +
      "luesEntry\022\013\n\003key\030\001 \001(\t\0222\n\005value\030\002 \001(\0132#." +
      "mojo.openapi.ReferenceableResponse:\0028\001\"\325" +
      "\n\n\006Schema\0222\n\rdiscriminator\030\001 \001(\0132\033.mojo." +
      "openapi.Discriminator\022\036\n\003xml\030\002 \001(\0132\021.moj" +
      "o.openapi.Xml\0225\n\rexternal_docs\030\003 \001(\0132\036.m" +
      "ojo.openapi.ExternalDocument\022\037\n\007example\030" +
      "\004 \001(\0132\016.mojo.core.Any\022\r\n\005title\030\n \001(\t\0221\n\013" +
      "description\030\013 \001(\0132\034.mojo.openapi.CachedD" +
      "ocument\022\'\n\004type\030\014 \001(\0162\031.mojo.openapi.Sch" +
      "ema.Type\022\016\n\006format\030\r \001(\t\022\023\n\013multiple_of\030" +
      "\016 \001(\003\022\017\n\007maximum\030\017 \001(\001\022\031\n\021exclusive_maxi" +
      "mum\030\020 \001(\001\022\017\n\007minimum\030\021 \001(\001\022\031\n\021exclusive_" +
      "minimum\030\022 \001(\001\022\022\n\nmax_length\030\023 \001(\004\022\022\n\nmin" +
      "_length\030\024 \001(\004\022!\n\007pattern\030\025 \001(\0132\020.mojo.co" +
      "re.Regex\0220\n\005items\030\026 \001(\0132!.mojo.openapi.R" +
      "eferenceableSchema\022\021\n\tmax_items\030\027 \001(\004\022\021\n" +
      "\tmin_items\030\030 \001(\004\022\024\n\014unique_items\030\031 \001(\010\0228" +
      "\n\nproperties\030\032 \003(\0132$.mojo.openapi.Schema" +
      ".PropertiesEntry\022@\n\025additional_propertie" +
      "s\030\033 \001(\0132!.mojo.openapi.ReferenceableSche" +
      "ma\022\026\n\016max_properties\030\034 \001(\004\022\026\n\016min_proper" +
      "ties\030\035 \001(\004\022\020\n\010required\030\036 \003(\t\022\036\n\004enum\030\037 \003" +
      "(\0132\020.mojo.core.Value\0221\n\006all_of\030# \003(\0132!.m" +
      "ojo.openapi.ReferenceableSchema\0221\n\006one_o" +
      "f\030$ \003(\0132!.mojo.openapi.ReferenceableSche" +
      "ma\0221\n\006any_of\030% \003(\0132!.mojo.openapi.Refere" +
      "nceableSchema\022.\n\003not\030& \001(\0132!.mojo.openap" +
      "i.ReferenceableSchema\022\037\n\007default\030( \001(\0132\016" +
      ".mojo.core.Any\022\020\n\010nullable\0302 \001(\010\022\021\n\tread" +
      "_only\0303 \001(\010\022\022\n\nwrite_only\0304 \001(\010\022\022\n\ndepre" +
      "cated\0305 \001(\010\032T\n\017PropertiesEntry\022\013\n\003key\030\001 " +
      "\001(\t\0220\n\005value\030\002 \001(\0132!.mojo.openapi.Refere" +
      "nceableSchema:\0028\001\"\222\001\n\004Type\022\024\n\020TYPE_UNSPE" +
      "CIFIED\020\000\022\r\n\tTYPE_NULL\020\001\022\020\n\014TYPE_INTEGER\020" +
      "\002\022\017\n\013TYPE_NUMBER\020\003\022\017\n\013TYPE_STRING\020\004\022\020\n\014T" +
      "YPE_BOOLEAN\020\005\022\016\n\nTYPE_ARRAY\020\n\022\017\n\013TYPE_OB" +
      "JECT\020\013\"\213\001\n\025ReferenceableResponse\022,\n\trefe" +
      "rence\030\001 \001(\0132\027.mojo.openapi.ReferenceH\000\022*" +
      "\n\010response\030\002 \001(\0132\026.mojo.openapi.Response" +
      "H\000B\030\n\026referenceable_response\"\217\001\n\026Referen" +
      "ceableParameter\022,\n\treference\030\001 \001(\0132\027.moj" +
      "o.openapi.ReferenceH\000\022,\n\tparameter\030\002 \001(\013" +
      "2\027.mojo.openapi.ParameterH\000B\031\n\027reference" +
      "able_parameter\"\231\001\n\030ReferenceableRequestB" +
      "ody\022,\n\treference\030\001 \001(\0132\027.mojo.openapi.Re" +
      "ferenceH\000\0221\n\014request_body\030\002 \001(\0132\031.mojo.o" +
      "penapi.RequestBodyH\000B\034\n\032referenceable_re" +
      "quest_body\"\203\001\n\023ReferenceableHeader\022,\n\tre" +
      "ference\030\001 \001(\0132\027.mojo.openapi.ReferenceH\000" +
      "\022&\n\006header\030\002 \001(\0132\024.mojo.openapi.HeaderH\000" +
      "B\026\n\024referenceable_header\"\213\001\n\025Referenceab" +
      "leCallback\022,\n\treference\030\001 \001(\0132\027.mojo.ope" +
      "napi.ReferenceH\000\022*\n\010callback\030\002 \001(\0132\026.moj" +
      "o.openapi.CallbackH\000B\030\n\026referenceable_ca" +
      "llback\"\203\001\n\023ReferenceableSchema\022,\n\trefere" +
      "nce\030\001 \001(\0132\027.mojo.openapi.ReferenceH\000\022&\n\006" +
      "schema\030\002 \001(\0132\024.mojo.openapi.SchemaH\000B\026\n\024" +
      "referenceable_schema\"\177\n\005Paths\022/\n\006values\030" +
      "\001 \003(\0132\037.mojo.openapi.Paths.ValuesEntry\032E" +
      "\n\013ValuesEntry\022\013\n\003key\030\001 \001(\t\022%\n\005value\030\002 \001(" +
      "\0132\026.mojo.openapi.PathItem:\0028\001\"\215\001\n\025Refere" +
      "nceablePathItem\022,\n\treference\030\001 \001(\0132\027.moj" +
      "o.openapi.ReferenceH\000\022+\n\tpath_item\030\002 \001(\013" +
      "2\026.mojo.openapi.PathItemH\000B\031\n\027referencea" +
      "ble_path_item*M\n\016HttpStatusCode\022\034\n\030HTTP_" +
      "STATUS_CODE_DEFAULT\020\000\022\035\n\031HTTP_STATUS_COD" +
      "E_CODE_200\020\001Be\n\031org.mojolang.mojo.openap" +
      "iB\014OpenapiProtoP\001Z8github.com/mojo-lang/" +
      "openapi/go/pkg/mojo/openapi;openapib\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.mojolang.mojo.core.AnyProto.getDescriptor(),
          org.mojolang.mojo.core.RegexProto.getDescriptor(),
          org.mojolang.mojo.core.ValueProto.getDescriptor(),
          org.mojolang.mojo.core.VersionProto.getDescriptor(),
          com.google.protobuf.MojoProtos.getDescriptor(),
          org.mojolang.mojo.openapi.CachedDocumentProto.getDescriptor(),
          org.mojolang.mojo.openapi.DiscriminatorProto.getDescriptor(),
          org.mojolang.mojo.openapi.ExternalDocumentProto.getDescriptor(),
          org.mojolang.mojo.openapi.InfoProto.getDescriptor(),
          org.mojolang.mojo.openapi.ReferenceProto.getDescriptor(),
          org.mojolang.mojo.openapi.ReferenceableExampleProto.getDescriptor(),
          org.mojolang.mojo.openapi.ReferenceableLinkProto.getDescriptor(),
          org.mojolang.mojo.openapi.ReferenceableSecuritySchemeProto.getDescriptor(),
          org.mojolang.mojo.openapi.SecurityRequirementProto.getDescriptor(),
          org.mojolang.mojo.openapi.ServerProto.getDescriptor(),
          org.mojolang.mojo.openapi.TagProto.getDescriptor(),
          org.mojolang.mojo.openapi.XmlProto.getDescriptor(),
        });
    internal_static_mojo_openapi_Components_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_mojo_openapi_Components_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_openapi_Components_descriptor,
        new java.lang.String[] { "Schemas", "Responses", "Parameters", "Examples", "RequestBodies", "Headers", "SecuritySchemes", "Links", "Callbacks", "PathItems", });
    internal_static_mojo_openapi_Components_SchemasEntry_descriptor =
      internal_static_mojo_openapi_Components_descriptor.getNestedTypes().get(0);
    internal_static_mojo_openapi_Components_SchemasEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_openapi_Components_SchemasEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_mojo_openapi_Components_ResponsesEntry_descriptor =
      internal_static_mojo_openapi_Components_descriptor.getNestedTypes().get(1);
    internal_static_mojo_openapi_Components_ResponsesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_openapi_Components_ResponsesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_mojo_openapi_Components_ParametersEntry_descriptor =
      internal_static_mojo_openapi_Components_descriptor.getNestedTypes().get(2);
    internal_static_mojo_openapi_Components_ParametersEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_openapi_Components_ParametersEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_mojo_openapi_Components_ExamplesEntry_descriptor =
      internal_static_mojo_openapi_Components_descriptor.getNestedTypes().get(3);
    internal_static_mojo_openapi_Components_ExamplesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_openapi_Components_ExamplesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_mojo_openapi_Components_RequestBodiesEntry_descriptor =
      internal_static_mojo_openapi_Components_descriptor.getNestedTypes().get(4);
    internal_static_mojo_openapi_Components_RequestBodiesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_openapi_Components_RequestBodiesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_mojo_openapi_Components_HeadersEntry_descriptor =
      internal_static_mojo_openapi_Components_descriptor.getNestedTypes().get(5);
    internal_static_mojo_openapi_Components_HeadersEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_openapi_Components_HeadersEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_mojo_openapi_Components_SecuritySchemesEntry_descriptor =
      internal_static_mojo_openapi_Components_descriptor.getNestedTypes().get(6);
    internal_static_mojo_openapi_Components_SecuritySchemesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_openapi_Components_SecuritySchemesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_mojo_openapi_Components_LinksEntry_descriptor =
      internal_static_mojo_openapi_Components_descriptor.getNestedTypes().get(7);
    internal_static_mojo_openapi_Components_LinksEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_openapi_Components_LinksEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_mojo_openapi_Components_CallbacksEntry_descriptor =
      internal_static_mojo_openapi_Components_descriptor.getNestedTypes().get(8);
    internal_static_mojo_openapi_Components_CallbacksEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_openapi_Components_CallbacksEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_mojo_openapi_Components_PathItemsEntry_descriptor =
      internal_static_mojo_openapi_Components_descriptor.getNestedTypes().get(9);
    internal_static_mojo_openapi_Components_PathItemsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_openapi_Components_PathItemsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_mojo_openapi_OpenAPI_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_mojo_openapi_OpenAPI_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_openapi_OpenAPI_descriptor,
        new java.lang.String[] { "Openapi", "Info", "Servers", "Paths", "Components", "Security", "Tags", "ExternalDocs", });
    internal_static_mojo_openapi_Callback_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_mojo_openapi_Callback_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_openapi_Callback_descriptor,
        new java.lang.String[] { "Values", });
    internal_static_mojo_openapi_Callback_ValuesEntry_descriptor =
      internal_static_mojo_openapi_Callback_descriptor.getNestedTypes().get(0);
    internal_static_mojo_openapi_Callback_ValuesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_openapi_Callback_ValuesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_mojo_openapi_Encoding_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_mojo_openapi_Encoding_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_openapi_Encoding_descriptor,
        new java.lang.String[] { "ContentType", "Headers", "Style", "Explode", "AllowReserved", });
    internal_static_mojo_openapi_Encoding_HeadersEntry_descriptor =
      internal_static_mojo_openapi_Encoding_descriptor.getNestedTypes().get(0);
    internal_static_mojo_openapi_Encoding_HeadersEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_openapi_Encoding_HeadersEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_mojo_openapi_Header_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_mojo_openapi_Header_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_openapi_Header_descriptor,
        new java.lang.String[] { "Name", "In", "Description", "Required", "Deprecated", "AllowEmptyValue", "Style", "Explode", "AllowReserved", "Schema", "Example", "Examples", "Content", });
    internal_static_mojo_openapi_Header_ExamplesEntry_descriptor =
      internal_static_mojo_openapi_Header_descriptor.getNestedTypes().get(0);
    internal_static_mojo_openapi_Header_ExamplesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_openapi_Header_ExamplesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_mojo_openapi_Header_ContentEntry_descriptor =
      internal_static_mojo_openapi_Header_descriptor.getNestedTypes().get(1);
    internal_static_mojo_openapi_Header_ContentEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_openapi_Header_ContentEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_mojo_openapi_MediaType_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_mojo_openapi_MediaType_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_openapi_MediaType_descriptor,
        new java.lang.String[] { "Schema", "Example", "Examples", "Encoding", });
    internal_static_mojo_openapi_MediaType_ExamplesEntry_descriptor =
      internal_static_mojo_openapi_MediaType_descriptor.getNestedTypes().get(0);
    internal_static_mojo_openapi_MediaType_ExamplesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_openapi_MediaType_ExamplesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_mojo_openapi_MediaType_EncodingEntry_descriptor =
      internal_static_mojo_openapi_MediaType_descriptor.getNestedTypes().get(1);
    internal_static_mojo_openapi_MediaType_EncodingEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_openapi_MediaType_EncodingEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_mojo_openapi_Operation_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_mojo_openapi_Operation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_openapi_Operation_descriptor,
        new java.lang.String[] { "Tags", "Summary", "Description", "ExternalDocs", "OperationId", "Parameters", "RequestBody", "Responses", "Callbacks", "Deprecated", "Security", "Servers", });
    internal_static_mojo_openapi_Operation_CallbacksEntry_descriptor =
      internal_static_mojo_openapi_Operation_descriptor.getNestedTypes().get(0);
    internal_static_mojo_openapi_Operation_CallbacksEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_openapi_Operation_CallbacksEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_mojo_openapi_Parameter_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_mojo_openapi_Parameter_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_openapi_Parameter_descriptor,
        new java.lang.String[] { "Name", "In", "Description", "Required", "Deprecated", "AllowEmptyValue", "Style", "Explode", "AllowReserved", "Schema", "Example", "Examples", "Content", });
    internal_static_mojo_openapi_Parameter_ExamplesEntry_descriptor =
      internal_static_mojo_openapi_Parameter_descriptor.getNestedTypes().get(0);
    internal_static_mojo_openapi_Parameter_ExamplesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_openapi_Parameter_ExamplesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_mojo_openapi_Parameter_ContentEntry_descriptor =
      internal_static_mojo_openapi_Parameter_descriptor.getNestedTypes().get(1);
    internal_static_mojo_openapi_Parameter_ContentEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_openapi_Parameter_ContentEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_mojo_openapi_PathItem_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_mojo_openapi_PathItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_openapi_PathItem_descriptor,
        new java.lang.String[] { "Ref", "Summary", "Description", "Get", "Put", "Post", "Delete", "Options", "Head", "Patch", "Trace", "Servers", "Parameters", });
    internal_static_mojo_openapi_RequestBody_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_mojo_openapi_RequestBody_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_openapi_RequestBody_descriptor,
        new java.lang.String[] { "Description", "Content", "Required", });
    internal_static_mojo_openapi_RequestBody_ContentEntry_descriptor =
      internal_static_mojo_openapi_RequestBody_descriptor.getNestedTypes().get(0);
    internal_static_mojo_openapi_RequestBody_ContentEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_openapi_RequestBody_ContentEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_mojo_openapi_Response_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_mojo_openapi_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_openapi_Response_descriptor,
        new java.lang.String[] { "Description", "Headers", "Content", "Links", });
    internal_static_mojo_openapi_Response_HeadersEntry_descriptor =
      internal_static_mojo_openapi_Response_descriptor.getNestedTypes().get(0);
    internal_static_mojo_openapi_Response_HeadersEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_openapi_Response_HeadersEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_mojo_openapi_Response_ContentEntry_descriptor =
      internal_static_mojo_openapi_Response_descriptor.getNestedTypes().get(1);
    internal_static_mojo_openapi_Response_ContentEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_openapi_Response_ContentEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_mojo_openapi_Response_LinksEntry_descriptor =
      internal_static_mojo_openapi_Response_descriptor.getNestedTypes().get(2);
    internal_static_mojo_openapi_Response_LinksEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_openapi_Response_LinksEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_mojo_openapi_Responses_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_mojo_openapi_Responses_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_openapi_Responses_descriptor,
        new java.lang.String[] { "Values", });
    internal_static_mojo_openapi_Responses_ValuesEntry_descriptor =
      internal_static_mojo_openapi_Responses_descriptor.getNestedTypes().get(0);
    internal_static_mojo_openapi_Responses_ValuesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_openapi_Responses_ValuesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_mojo_openapi_Schema_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_mojo_openapi_Schema_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_openapi_Schema_descriptor,
        new java.lang.String[] { "Discriminator", "Xml", "ExternalDocs", "Example", "Title", "Description", "Type", "Format", "MultipleOf", "Maximum", "ExclusiveMaximum", "Minimum", "ExclusiveMinimum", "MaxLength", "MinLength", "Pattern", "Items", "MaxItems", "MinItems", "UniqueItems", "Properties", "AdditionalProperties", "MaxProperties", "MinProperties", "Required", "Enum", "AllOf", "OneOf", "AnyOf", "Not", "Default", "Nullable", "ReadOnly", "WriteOnly", "Deprecated", });
    internal_static_mojo_openapi_Schema_PropertiesEntry_descriptor =
      internal_static_mojo_openapi_Schema_descriptor.getNestedTypes().get(0);
    internal_static_mojo_openapi_Schema_PropertiesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_openapi_Schema_PropertiesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_mojo_openapi_ReferenceableResponse_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_mojo_openapi_ReferenceableResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_openapi_ReferenceableResponse_descriptor,
        new java.lang.String[] { "Reference", "Response", "ReferenceableResponse", });
    internal_static_mojo_openapi_ReferenceableParameter_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_mojo_openapi_ReferenceableParameter_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_openapi_ReferenceableParameter_descriptor,
        new java.lang.String[] { "Reference", "Parameter", "ReferenceableParameter", });
    internal_static_mojo_openapi_ReferenceableRequestBody_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_mojo_openapi_ReferenceableRequestBody_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_openapi_ReferenceableRequestBody_descriptor,
        new java.lang.String[] { "Reference", "RequestBody", "ReferenceableRequestBody", });
    internal_static_mojo_openapi_ReferenceableHeader_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_mojo_openapi_ReferenceableHeader_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_openapi_ReferenceableHeader_descriptor,
        new java.lang.String[] { "Reference", "Header", "ReferenceableHeader", });
    internal_static_mojo_openapi_ReferenceableCallback_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_mojo_openapi_ReferenceableCallback_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_openapi_ReferenceableCallback_descriptor,
        new java.lang.String[] { "Reference", "Callback", "ReferenceableCallback", });
    internal_static_mojo_openapi_ReferenceableSchema_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_mojo_openapi_ReferenceableSchema_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_openapi_ReferenceableSchema_descriptor,
        new java.lang.String[] { "Reference", "Schema", "ReferenceableSchema", });
    internal_static_mojo_openapi_Paths_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_mojo_openapi_Paths_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_openapi_Paths_descriptor,
        new java.lang.String[] { "Values", });
    internal_static_mojo_openapi_Paths_ValuesEntry_descriptor =
      internal_static_mojo_openapi_Paths_descriptor.getNestedTypes().get(0);
    internal_static_mojo_openapi_Paths_ValuesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_openapi_Paths_ValuesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_mojo_openapi_ReferenceablePathItem_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_mojo_openapi_ReferenceablePathItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_openapi_ReferenceablePathItem_descriptor,
        new java.lang.String[] { "Reference", "PathItem", "ReferenceablePathItem", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.protobuf.MojoProtos.alias);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    org.mojolang.mojo.core.AnyProto.getDescriptor();
    org.mojolang.mojo.core.RegexProto.getDescriptor();
    org.mojolang.mojo.core.ValueProto.getDescriptor();
    org.mojolang.mojo.core.VersionProto.getDescriptor();
    com.google.protobuf.MojoProtos.getDescriptor();
    org.mojolang.mojo.openapi.CachedDocumentProto.getDescriptor();
    org.mojolang.mojo.openapi.DiscriminatorProto.getDescriptor();
    org.mojolang.mojo.openapi.ExternalDocumentProto.getDescriptor();
    org.mojolang.mojo.openapi.InfoProto.getDescriptor();
    org.mojolang.mojo.openapi.ReferenceProto.getDescriptor();
    org.mojolang.mojo.openapi.ReferenceableExampleProto.getDescriptor();
    org.mojolang.mojo.openapi.ReferenceableLinkProto.getDescriptor();
    org.mojolang.mojo.openapi.ReferenceableSecuritySchemeProto.getDescriptor();
    org.mojolang.mojo.openapi.SecurityRequirementProto.getDescriptor();
    org.mojolang.mojo.openapi.ServerProto.getDescriptor();
    org.mojolang.mojo.openapi.TagProto.getDescriptor();
    org.mojolang.mojo.openapi.XmlProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
