// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/openapi/referenceable_link.proto

package org.mojolang.mojo.openapi;

/**
 * Protobuf type {@code mojo.openapi.ReferenceableLink}
 */
public final class ReferenceableLink extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:mojo.openapi.ReferenceableLink)
    ReferenceableLinkOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ReferenceableLink.newBuilder() to construct.
  private ReferenceableLink(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ReferenceableLink() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ReferenceableLink();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ReferenceableLink(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            org.mojolang.mojo.openapi.Reference.Builder subBuilder = null;
            if (referenceableLinkCase_ == 1) {
              subBuilder = ((org.mojolang.mojo.openapi.Reference) referenceableLink_).toBuilder();
            }
            referenceableLink_ =
                input.readMessage(org.mojolang.mojo.openapi.Reference.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((org.mojolang.mojo.openapi.Reference) referenceableLink_);
              referenceableLink_ = subBuilder.buildPartial();
            }
            referenceableLinkCase_ = 1;
            break;
          }
          case 18: {
            org.mojolang.mojo.openapi.Link.Builder subBuilder = null;
            if (referenceableLinkCase_ == 2) {
              subBuilder = ((org.mojolang.mojo.openapi.Link) referenceableLink_).toBuilder();
            }
            referenceableLink_ =
                input.readMessage(org.mojolang.mojo.openapi.Link.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((org.mojolang.mojo.openapi.Link) referenceableLink_);
              referenceableLink_ = subBuilder.buildPartial();
            }
            referenceableLinkCase_ = 2;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.mojolang.mojo.openapi.ReferenceableLinkProto.internal_static_mojo_openapi_ReferenceableLink_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.mojolang.mojo.openapi.ReferenceableLinkProto.internal_static_mojo_openapi_ReferenceableLink_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.mojolang.mojo.openapi.ReferenceableLink.class, org.mojolang.mojo.openapi.ReferenceableLink.Builder.class);
  }

  private int referenceableLinkCase_ = 0;
  private java.lang.Object referenceableLink_;
  public enum ReferenceableLinkCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    REFERENCE(1),
    LINK(2),
    REFERENCEABLELINK_NOT_SET(0);
    private final int value;
    private ReferenceableLinkCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ReferenceableLinkCase valueOf(int value) {
      return forNumber(value);
    }

    public static ReferenceableLinkCase forNumber(int value) {
      switch (value) {
        case 1: return REFERENCE;
        case 2: return LINK;
        case 0: return REFERENCEABLELINK_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public ReferenceableLinkCase
  getReferenceableLinkCase() {
    return ReferenceableLinkCase.forNumber(
        referenceableLinkCase_);
  }

  public static final int REFERENCE_FIELD_NUMBER = 1;
  /**
   * <code>.mojo.openapi.Reference reference = 1;</code>
   * @return Whether the reference field is set.
   */
  @java.lang.Override
  public boolean hasReference() {
    return referenceableLinkCase_ == 1;
  }
  /**
   * <code>.mojo.openapi.Reference reference = 1;</code>
   * @return The reference.
   */
  @java.lang.Override
  public org.mojolang.mojo.openapi.Reference getReference() {
    if (referenceableLinkCase_ == 1) {
       return (org.mojolang.mojo.openapi.Reference) referenceableLink_;
    }
    return org.mojolang.mojo.openapi.Reference.getDefaultInstance();
  }
  /**
   * <code>.mojo.openapi.Reference reference = 1;</code>
   */
  @java.lang.Override
  public org.mojolang.mojo.openapi.ReferenceOrBuilder getReferenceOrBuilder() {
    if (referenceableLinkCase_ == 1) {
       return (org.mojolang.mojo.openapi.Reference) referenceableLink_;
    }
    return org.mojolang.mojo.openapi.Reference.getDefaultInstance();
  }

  public static final int LINK_FIELD_NUMBER = 2;
  /**
   * <code>.mojo.openapi.Link link = 2;</code>
   * @return Whether the link field is set.
   */
  @java.lang.Override
  public boolean hasLink() {
    return referenceableLinkCase_ == 2;
  }
  /**
   * <code>.mojo.openapi.Link link = 2;</code>
   * @return The link.
   */
  @java.lang.Override
  public org.mojolang.mojo.openapi.Link getLink() {
    if (referenceableLinkCase_ == 2) {
       return (org.mojolang.mojo.openapi.Link) referenceableLink_;
    }
    return org.mojolang.mojo.openapi.Link.getDefaultInstance();
  }
  /**
   * <code>.mojo.openapi.Link link = 2;</code>
   */
  @java.lang.Override
  public org.mojolang.mojo.openapi.LinkOrBuilder getLinkOrBuilder() {
    if (referenceableLinkCase_ == 2) {
       return (org.mojolang.mojo.openapi.Link) referenceableLink_;
    }
    return org.mojolang.mojo.openapi.Link.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (referenceableLinkCase_ == 1) {
      output.writeMessage(1, (org.mojolang.mojo.openapi.Reference) referenceableLink_);
    }
    if (referenceableLinkCase_ == 2) {
      output.writeMessage(2, (org.mojolang.mojo.openapi.Link) referenceableLink_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (referenceableLinkCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (org.mojolang.mojo.openapi.Reference) referenceableLink_);
    }
    if (referenceableLinkCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (org.mojolang.mojo.openapi.Link) referenceableLink_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.mojolang.mojo.openapi.ReferenceableLink)) {
      return super.equals(obj);
    }
    org.mojolang.mojo.openapi.ReferenceableLink other = (org.mojolang.mojo.openapi.ReferenceableLink) obj;

    if (!getReferenceableLinkCase().equals(other.getReferenceableLinkCase())) return false;
    switch (referenceableLinkCase_) {
      case 1:
        if (!getReference()
            .equals(other.getReference())) return false;
        break;
      case 2:
        if (!getLink()
            .equals(other.getLink())) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (referenceableLinkCase_) {
      case 1:
        hash = (37 * hash) + REFERENCE_FIELD_NUMBER;
        hash = (53 * hash) + getReference().hashCode();
        break;
      case 2:
        hash = (37 * hash) + LINK_FIELD_NUMBER;
        hash = (53 * hash) + getLink().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.mojolang.mojo.openapi.ReferenceableLink parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.mojolang.mojo.openapi.ReferenceableLink parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.mojolang.mojo.openapi.ReferenceableLink parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.mojolang.mojo.openapi.ReferenceableLink parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.mojolang.mojo.openapi.ReferenceableLink parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.mojolang.mojo.openapi.ReferenceableLink parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.mojolang.mojo.openapi.ReferenceableLink parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.mojolang.mojo.openapi.ReferenceableLink parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.mojolang.mojo.openapi.ReferenceableLink parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.mojolang.mojo.openapi.ReferenceableLink parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.mojolang.mojo.openapi.ReferenceableLink parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.mojolang.mojo.openapi.ReferenceableLink parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.mojolang.mojo.openapi.ReferenceableLink prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code mojo.openapi.ReferenceableLink}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:mojo.openapi.ReferenceableLink)
      org.mojolang.mojo.openapi.ReferenceableLinkOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.mojolang.mojo.openapi.ReferenceableLinkProto.internal_static_mojo_openapi_ReferenceableLink_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.mojolang.mojo.openapi.ReferenceableLinkProto.internal_static_mojo_openapi_ReferenceableLink_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.mojolang.mojo.openapi.ReferenceableLink.class, org.mojolang.mojo.openapi.ReferenceableLink.Builder.class);
    }

    // Construct using org.mojolang.mojo.openapi.ReferenceableLink.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      referenceableLinkCase_ = 0;
      referenceableLink_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.mojolang.mojo.openapi.ReferenceableLinkProto.internal_static_mojo_openapi_ReferenceableLink_descriptor;
    }

    @java.lang.Override
    public org.mojolang.mojo.openapi.ReferenceableLink getDefaultInstanceForType() {
      return org.mojolang.mojo.openapi.ReferenceableLink.getDefaultInstance();
    }

    @java.lang.Override
    public org.mojolang.mojo.openapi.ReferenceableLink build() {
      org.mojolang.mojo.openapi.ReferenceableLink result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.mojolang.mojo.openapi.ReferenceableLink buildPartial() {
      org.mojolang.mojo.openapi.ReferenceableLink result = new org.mojolang.mojo.openapi.ReferenceableLink(this);
      if (referenceableLinkCase_ == 1) {
        if (referenceBuilder_ == null) {
          result.referenceableLink_ = referenceableLink_;
        } else {
          result.referenceableLink_ = referenceBuilder_.build();
        }
      }
      if (referenceableLinkCase_ == 2) {
        if (linkBuilder_ == null) {
          result.referenceableLink_ = referenceableLink_;
        } else {
          result.referenceableLink_ = linkBuilder_.build();
        }
      }
      result.referenceableLinkCase_ = referenceableLinkCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.mojolang.mojo.openapi.ReferenceableLink) {
        return mergeFrom((org.mojolang.mojo.openapi.ReferenceableLink)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.mojolang.mojo.openapi.ReferenceableLink other) {
      if (other == org.mojolang.mojo.openapi.ReferenceableLink.getDefaultInstance()) return this;
      switch (other.getReferenceableLinkCase()) {
        case REFERENCE: {
          mergeReference(other.getReference());
          break;
        }
        case LINK: {
          mergeLink(other.getLink());
          break;
        }
        case REFERENCEABLELINK_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.mojolang.mojo.openapi.ReferenceableLink parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.mojolang.mojo.openapi.ReferenceableLink) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int referenceableLinkCase_ = 0;
    private java.lang.Object referenceableLink_;
    public ReferenceableLinkCase
        getReferenceableLinkCase() {
      return ReferenceableLinkCase.forNumber(
          referenceableLinkCase_);
    }

    public Builder clearReferenceableLink() {
      referenceableLinkCase_ = 0;
      referenceableLink_ = null;
      onChanged();
      return this;
    }


    private com.google.protobuf.SingleFieldBuilderV3<
        org.mojolang.mojo.openapi.Reference, org.mojolang.mojo.openapi.Reference.Builder, org.mojolang.mojo.openapi.ReferenceOrBuilder> referenceBuilder_;
    /**
     * <code>.mojo.openapi.Reference reference = 1;</code>
     * @return Whether the reference field is set.
     */
    @java.lang.Override
    public boolean hasReference() {
      return referenceableLinkCase_ == 1;
    }
    /**
     * <code>.mojo.openapi.Reference reference = 1;</code>
     * @return The reference.
     */
    @java.lang.Override
    public org.mojolang.mojo.openapi.Reference getReference() {
      if (referenceBuilder_ == null) {
        if (referenceableLinkCase_ == 1) {
          return (org.mojolang.mojo.openapi.Reference) referenceableLink_;
        }
        return org.mojolang.mojo.openapi.Reference.getDefaultInstance();
      } else {
        if (referenceableLinkCase_ == 1) {
          return referenceBuilder_.getMessage();
        }
        return org.mojolang.mojo.openapi.Reference.getDefaultInstance();
      }
    }
    /**
     * <code>.mojo.openapi.Reference reference = 1;</code>
     */
    public Builder setReference(org.mojolang.mojo.openapi.Reference value) {
      if (referenceBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        referenceableLink_ = value;
        onChanged();
      } else {
        referenceBuilder_.setMessage(value);
      }
      referenceableLinkCase_ = 1;
      return this;
    }
    /**
     * <code>.mojo.openapi.Reference reference = 1;</code>
     */
    public Builder setReference(
        org.mojolang.mojo.openapi.Reference.Builder builderForValue) {
      if (referenceBuilder_ == null) {
        referenceableLink_ = builderForValue.build();
        onChanged();
      } else {
        referenceBuilder_.setMessage(builderForValue.build());
      }
      referenceableLinkCase_ = 1;
      return this;
    }
    /**
     * <code>.mojo.openapi.Reference reference = 1;</code>
     */
    public Builder mergeReference(org.mojolang.mojo.openapi.Reference value) {
      if (referenceBuilder_ == null) {
        if (referenceableLinkCase_ == 1 &&
            referenceableLink_ != org.mojolang.mojo.openapi.Reference.getDefaultInstance()) {
          referenceableLink_ = org.mojolang.mojo.openapi.Reference.newBuilder((org.mojolang.mojo.openapi.Reference) referenceableLink_)
              .mergeFrom(value).buildPartial();
        } else {
          referenceableLink_ = value;
        }
        onChanged();
      } else {
        if (referenceableLinkCase_ == 1) {
          referenceBuilder_.mergeFrom(value);
        }
        referenceBuilder_.setMessage(value);
      }
      referenceableLinkCase_ = 1;
      return this;
    }
    /**
     * <code>.mojo.openapi.Reference reference = 1;</code>
     */
    public Builder clearReference() {
      if (referenceBuilder_ == null) {
        if (referenceableLinkCase_ == 1) {
          referenceableLinkCase_ = 0;
          referenceableLink_ = null;
          onChanged();
        }
      } else {
        if (referenceableLinkCase_ == 1) {
          referenceableLinkCase_ = 0;
          referenceableLink_ = null;
        }
        referenceBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.mojo.openapi.Reference reference = 1;</code>
     */
    public org.mojolang.mojo.openapi.Reference.Builder getReferenceBuilder() {
      return getReferenceFieldBuilder().getBuilder();
    }
    /**
     * <code>.mojo.openapi.Reference reference = 1;</code>
     */
    @java.lang.Override
    public org.mojolang.mojo.openapi.ReferenceOrBuilder getReferenceOrBuilder() {
      if ((referenceableLinkCase_ == 1) && (referenceBuilder_ != null)) {
        return referenceBuilder_.getMessageOrBuilder();
      } else {
        if (referenceableLinkCase_ == 1) {
          return (org.mojolang.mojo.openapi.Reference) referenceableLink_;
        }
        return org.mojolang.mojo.openapi.Reference.getDefaultInstance();
      }
    }
    /**
     * <code>.mojo.openapi.Reference reference = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.mojolang.mojo.openapi.Reference, org.mojolang.mojo.openapi.Reference.Builder, org.mojolang.mojo.openapi.ReferenceOrBuilder> 
        getReferenceFieldBuilder() {
      if (referenceBuilder_ == null) {
        if (!(referenceableLinkCase_ == 1)) {
          referenceableLink_ = org.mojolang.mojo.openapi.Reference.getDefaultInstance();
        }
        referenceBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.mojolang.mojo.openapi.Reference, org.mojolang.mojo.openapi.Reference.Builder, org.mojolang.mojo.openapi.ReferenceOrBuilder>(
                (org.mojolang.mojo.openapi.Reference) referenceableLink_,
                getParentForChildren(),
                isClean());
        referenceableLink_ = null;
      }
      referenceableLinkCase_ = 1;
      onChanged();;
      return referenceBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        org.mojolang.mojo.openapi.Link, org.mojolang.mojo.openapi.Link.Builder, org.mojolang.mojo.openapi.LinkOrBuilder> linkBuilder_;
    /**
     * <code>.mojo.openapi.Link link = 2;</code>
     * @return Whether the link field is set.
     */
    @java.lang.Override
    public boolean hasLink() {
      return referenceableLinkCase_ == 2;
    }
    /**
     * <code>.mojo.openapi.Link link = 2;</code>
     * @return The link.
     */
    @java.lang.Override
    public org.mojolang.mojo.openapi.Link getLink() {
      if (linkBuilder_ == null) {
        if (referenceableLinkCase_ == 2) {
          return (org.mojolang.mojo.openapi.Link) referenceableLink_;
        }
        return org.mojolang.mojo.openapi.Link.getDefaultInstance();
      } else {
        if (referenceableLinkCase_ == 2) {
          return linkBuilder_.getMessage();
        }
        return org.mojolang.mojo.openapi.Link.getDefaultInstance();
      }
    }
    /**
     * <code>.mojo.openapi.Link link = 2;</code>
     */
    public Builder setLink(org.mojolang.mojo.openapi.Link value) {
      if (linkBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        referenceableLink_ = value;
        onChanged();
      } else {
        linkBuilder_.setMessage(value);
      }
      referenceableLinkCase_ = 2;
      return this;
    }
    /**
     * <code>.mojo.openapi.Link link = 2;</code>
     */
    public Builder setLink(
        org.mojolang.mojo.openapi.Link.Builder builderForValue) {
      if (linkBuilder_ == null) {
        referenceableLink_ = builderForValue.build();
        onChanged();
      } else {
        linkBuilder_.setMessage(builderForValue.build());
      }
      referenceableLinkCase_ = 2;
      return this;
    }
    /**
     * <code>.mojo.openapi.Link link = 2;</code>
     */
    public Builder mergeLink(org.mojolang.mojo.openapi.Link value) {
      if (linkBuilder_ == null) {
        if (referenceableLinkCase_ == 2 &&
            referenceableLink_ != org.mojolang.mojo.openapi.Link.getDefaultInstance()) {
          referenceableLink_ = org.mojolang.mojo.openapi.Link.newBuilder((org.mojolang.mojo.openapi.Link) referenceableLink_)
              .mergeFrom(value).buildPartial();
        } else {
          referenceableLink_ = value;
        }
        onChanged();
      } else {
        if (referenceableLinkCase_ == 2) {
          linkBuilder_.mergeFrom(value);
        }
        linkBuilder_.setMessage(value);
      }
      referenceableLinkCase_ = 2;
      return this;
    }
    /**
     * <code>.mojo.openapi.Link link = 2;</code>
     */
    public Builder clearLink() {
      if (linkBuilder_ == null) {
        if (referenceableLinkCase_ == 2) {
          referenceableLinkCase_ = 0;
          referenceableLink_ = null;
          onChanged();
        }
      } else {
        if (referenceableLinkCase_ == 2) {
          referenceableLinkCase_ = 0;
          referenceableLink_ = null;
        }
        linkBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.mojo.openapi.Link link = 2;</code>
     */
    public org.mojolang.mojo.openapi.Link.Builder getLinkBuilder() {
      return getLinkFieldBuilder().getBuilder();
    }
    /**
     * <code>.mojo.openapi.Link link = 2;</code>
     */
    @java.lang.Override
    public org.mojolang.mojo.openapi.LinkOrBuilder getLinkOrBuilder() {
      if ((referenceableLinkCase_ == 2) && (linkBuilder_ != null)) {
        return linkBuilder_.getMessageOrBuilder();
      } else {
        if (referenceableLinkCase_ == 2) {
          return (org.mojolang.mojo.openapi.Link) referenceableLink_;
        }
        return org.mojolang.mojo.openapi.Link.getDefaultInstance();
      }
    }
    /**
     * <code>.mojo.openapi.Link link = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.mojolang.mojo.openapi.Link, org.mojolang.mojo.openapi.Link.Builder, org.mojolang.mojo.openapi.LinkOrBuilder> 
        getLinkFieldBuilder() {
      if (linkBuilder_ == null) {
        if (!(referenceableLinkCase_ == 2)) {
          referenceableLink_ = org.mojolang.mojo.openapi.Link.getDefaultInstance();
        }
        linkBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.mojolang.mojo.openapi.Link, org.mojolang.mojo.openapi.Link.Builder, org.mojolang.mojo.openapi.LinkOrBuilder>(
                (org.mojolang.mojo.openapi.Link) referenceableLink_,
                getParentForChildren(),
                isClean());
        referenceableLink_ = null;
      }
      referenceableLinkCase_ = 2;
      onChanged();;
      return linkBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:mojo.openapi.ReferenceableLink)
  }

  // @@protoc_insertion_point(class_scope:mojo.openapi.ReferenceableLink)
  private static final org.mojolang.mojo.openapi.ReferenceableLink DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.mojolang.mojo.openapi.ReferenceableLink();
  }

  public static org.mojolang.mojo.openapi.ReferenceableLink getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ReferenceableLink>
      PARSER = new com.google.protobuf.AbstractParser<ReferenceableLink>() {
    @java.lang.Override
    public ReferenceableLink parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ReferenceableLink(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ReferenceableLink> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ReferenceableLink> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.mojolang.mojo.openapi.ReferenceableLink getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

