// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/openapi/openapi.proto

package org.mojolang.mojo.openapi;

public interface ResponsesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mojo.openapi.Responses)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>map&lt;string, .mojo.openapi.ReferenceableResponse&gt; values = 1;</code>
   */
  int getValuesCount();
  /**
   * <code>map&lt;string, .mojo.openapi.ReferenceableResponse&gt; values = 1;</code>
   */
  boolean containsValues(
      java.lang.String key);
  /**
   * Use {@link #getValuesMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, org.mojolang.mojo.openapi.ReferenceableResponse>
  getValues();
  /**
   * <code>map&lt;string, .mojo.openapi.ReferenceableResponse&gt; values = 1;</code>
   */
  java.util.Map<java.lang.String, org.mojolang.mojo.openapi.ReferenceableResponse>
  getValuesMap();
  /**
   * <code>map&lt;string, .mojo.openapi.ReferenceableResponse&gt; values = 1;</code>
   */

  org.mojolang.mojo.openapi.ReferenceableResponse getValuesOrDefault(
      java.lang.String key,
      org.mojolang.mojo.openapi.ReferenceableResponse defaultValue);
  /**
   * <code>map&lt;string, .mojo.openapi.ReferenceableResponse&gt; values = 1;</code>
   */

  org.mojolang.mojo.openapi.ReferenceableResponse getValuesOrThrow(
      java.lang.String key);
}
