// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/openapi/security_requirement.proto

package org.mojolang.mojo.openapi;

public final class SecurityRequirementProto {
  private SecurityRequirementProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_openapi_SecurityRequirement_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_openapi_SecurityRequirement_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_openapi_SecurityRequirement_ValuesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_openapi_SecurityRequirement_ValuesEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\'mojo/openapi/security_requirement.prot" +
      "o\022\014mojo.openapi\032\025mojo/core/boxed.proto\"\227" +
      "\001\n\023SecurityRequirement\022=\n\006values\030\001 \003(\0132-" +
      ".mojo.openapi.SecurityRequirement.Values" +
      "Entry\032A\n\013ValuesEntry\022\013\n\003key\030\001 \001(\t\022!\n\005val" +
      "ue\030\002 \001(\0132\022.mojo.core.Strings:\0028\001Bq\n\031org." +
      "mojolang.mojo.openapiB\030SecurityRequireme" +
      "ntProtoP\001Z8github.com/mojo-lang/openapi/" +
      "go/pkg/mojo/openapi;openapib\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.mojolang.mojo.core.BoxedProto.getDescriptor(),
        });
    internal_static_mojo_openapi_SecurityRequirement_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_mojo_openapi_SecurityRequirement_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_openapi_SecurityRequirement_descriptor,
        new java.lang.String[] { "Values", });
    internal_static_mojo_openapi_SecurityRequirement_ValuesEntry_descriptor =
      internal_static_mojo_openapi_SecurityRequirement_descriptor.getNestedTypes().get(0);
    internal_static_mojo_openapi_SecurityRequirement_ValuesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_openapi_SecurityRequirement_ValuesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    org.mojolang.mojo.core.BoxedProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
