// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/openapi/tag.proto

package org.mojolang.mojo.openapi;

/**
 * Protobuf type {@code mojo.openapi.Tag}
 */
public final class Tag extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:mojo.openapi.Tag)
    TagOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Tag.newBuilder() to construct.
  private Tag(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Tag() {
    name_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Tag();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Tag(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 26: {
            org.mojolang.mojo.openapi.CachedDocument.Builder subBuilder = null;
            if (description_ != null) {
              subBuilder = description_.toBuilder();
            }
            description_ = input.readMessage(org.mojolang.mojo.openapi.CachedDocument.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(description_);
              description_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            org.mojolang.mojo.openapi.ExternalDocument.Builder subBuilder = null;
            if (externalDocs_ != null) {
              subBuilder = externalDocs_.toBuilder();
            }
            externalDocs_ = input.readMessage(org.mojolang.mojo.openapi.ExternalDocument.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(externalDocs_);
              externalDocs_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.mojolang.mojo.openapi.TagProto.internal_static_mojo_openapi_Tag_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.mojolang.mojo.openapi.TagProto.internal_static_mojo_openapi_Tag_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.mojolang.mojo.openapi.Tag.class, org.mojolang.mojo.openapi.Tag.Builder.class);
  }

  public static final int NAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object name_;
  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DESCRIPTION_FIELD_NUMBER = 3;
  private org.mojolang.mojo.openapi.CachedDocument description_;
  /**
   * <code>.mojo.openapi.CachedDocument description = 3;</code>
   * @return Whether the description field is set.
   */
  @java.lang.Override
  public boolean hasDescription() {
    return description_ != null;
  }
  /**
   * <code>.mojo.openapi.CachedDocument description = 3;</code>
   * @return The description.
   */
  @java.lang.Override
  public org.mojolang.mojo.openapi.CachedDocument getDescription() {
    return description_ == null ? org.mojolang.mojo.openapi.CachedDocument.getDefaultInstance() : description_;
  }
  /**
   * <code>.mojo.openapi.CachedDocument description = 3;</code>
   */
  @java.lang.Override
  public org.mojolang.mojo.openapi.CachedDocumentOrBuilder getDescriptionOrBuilder() {
    return getDescription();
  }

  public static final int EXTERNAL_DOCS_FIELD_NUMBER = 4;
  private org.mojolang.mojo.openapi.ExternalDocument externalDocs_;
  /**
   * <code>.mojo.openapi.ExternalDocument external_docs = 4;</code>
   * @return Whether the externalDocs field is set.
   */
  @java.lang.Override
  public boolean hasExternalDocs() {
    return externalDocs_ != null;
  }
  /**
   * <code>.mojo.openapi.ExternalDocument external_docs = 4;</code>
   * @return The externalDocs.
   */
  @java.lang.Override
  public org.mojolang.mojo.openapi.ExternalDocument getExternalDocs() {
    return externalDocs_ == null ? org.mojolang.mojo.openapi.ExternalDocument.getDefaultInstance() : externalDocs_;
  }
  /**
   * <code>.mojo.openapi.ExternalDocument external_docs = 4;</code>
   */
  @java.lang.Override
  public org.mojolang.mojo.openapi.ExternalDocumentOrBuilder getExternalDocsOrBuilder() {
    return getExternalDocs();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
    }
    if (description_ != null) {
      output.writeMessage(3, getDescription());
    }
    if (externalDocs_ != null) {
      output.writeMessage(4, getExternalDocs());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
    }
    if (description_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getDescription());
    }
    if (externalDocs_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getExternalDocs());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.mojolang.mojo.openapi.Tag)) {
      return super.equals(obj);
    }
    org.mojolang.mojo.openapi.Tag other = (org.mojolang.mojo.openapi.Tag) obj;

    if (!getName()
        .equals(other.getName())) return false;
    if (hasDescription() != other.hasDescription()) return false;
    if (hasDescription()) {
      if (!getDescription()
          .equals(other.getDescription())) return false;
    }
    if (hasExternalDocs() != other.hasExternalDocs()) return false;
    if (hasExternalDocs()) {
      if (!getExternalDocs()
          .equals(other.getExternalDocs())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    if (hasDescription()) {
      hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
      hash = (53 * hash) + getDescription().hashCode();
    }
    if (hasExternalDocs()) {
      hash = (37 * hash) + EXTERNAL_DOCS_FIELD_NUMBER;
      hash = (53 * hash) + getExternalDocs().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.mojolang.mojo.openapi.Tag parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.mojolang.mojo.openapi.Tag parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.mojolang.mojo.openapi.Tag parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.mojolang.mojo.openapi.Tag parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.mojolang.mojo.openapi.Tag parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.mojolang.mojo.openapi.Tag parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.mojolang.mojo.openapi.Tag parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.mojolang.mojo.openapi.Tag parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.mojolang.mojo.openapi.Tag parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.mojolang.mojo.openapi.Tag parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.mojolang.mojo.openapi.Tag parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.mojolang.mojo.openapi.Tag parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.mojolang.mojo.openapi.Tag prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code mojo.openapi.Tag}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:mojo.openapi.Tag)
      org.mojolang.mojo.openapi.TagOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.mojolang.mojo.openapi.TagProto.internal_static_mojo_openapi_Tag_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.mojolang.mojo.openapi.TagProto.internal_static_mojo_openapi_Tag_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.mojolang.mojo.openapi.Tag.class, org.mojolang.mojo.openapi.Tag.Builder.class);
    }

    // Construct using org.mojolang.mojo.openapi.Tag.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      name_ = "";

      if (descriptionBuilder_ == null) {
        description_ = null;
      } else {
        description_ = null;
        descriptionBuilder_ = null;
      }
      if (externalDocsBuilder_ == null) {
        externalDocs_ = null;
      } else {
        externalDocs_ = null;
        externalDocsBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.mojolang.mojo.openapi.TagProto.internal_static_mojo_openapi_Tag_descriptor;
    }

    @java.lang.Override
    public org.mojolang.mojo.openapi.Tag getDefaultInstanceForType() {
      return org.mojolang.mojo.openapi.Tag.getDefaultInstance();
    }

    @java.lang.Override
    public org.mojolang.mojo.openapi.Tag build() {
      org.mojolang.mojo.openapi.Tag result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.mojolang.mojo.openapi.Tag buildPartial() {
      org.mojolang.mojo.openapi.Tag result = new org.mojolang.mojo.openapi.Tag(this);
      result.name_ = name_;
      if (descriptionBuilder_ == null) {
        result.description_ = description_;
      } else {
        result.description_ = descriptionBuilder_.build();
      }
      if (externalDocsBuilder_ == null) {
        result.externalDocs_ = externalDocs_;
      } else {
        result.externalDocs_ = externalDocsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.mojolang.mojo.openapi.Tag) {
        return mergeFrom((org.mojolang.mojo.openapi.Tag)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.mojolang.mojo.openapi.Tag other) {
      if (other == org.mojolang.mojo.openapi.Tag.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (other.hasDescription()) {
        mergeDescription(other.getDescription());
      }
      if (other.hasExternalDocs()) {
        mergeExternalDocs(other.getExternalDocs());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.mojolang.mojo.openapi.Tag parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.mojolang.mojo.openapi.Tag) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private org.mojolang.mojo.openapi.CachedDocument description_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.mojolang.mojo.openapi.CachedDocument, org.mojolang.mojo.openapi.CachedDocument.Builder, org.mojolang.mojo.openapi.CachedDocumentOrBuilder> descriptionBuilder_;
    /**
     * <code>.mojo.openapi.CachedDocument description = 3;</code>
     * @return Whether the description field is set.
     */
    public boolean hasDescription() {
      return descriptionBuilder_ != null || description_ != null;
    }
    /**
     * <code>.mojo.openapi.CachedDocument description = 3;</code>
     * @return The description.
     */
    public org.mojolang.mojo.openapi.CachedDocument getDescription() {
      if (descriptionBuilder_ == null) {
        return description_ == null ? org.mojolang.mojo.openapi.CachedDocument.getDefaultInstance() : description_;
      } else {
        return descriptionBuilder_.getMessage();
      }
    }
    /**
     * <code>.mojo.openapi.CachedDocument description = 3;</code>
     */
    public Builder setDescription(org.mojolang.mojo.openapi.CachedDocument value) {
      if (descriptionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        description_ = value;
        onChanged();
      } else {
        descriptionBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.mojo.openapi.CachedDocument description = 3;</code>
     */
    public Builder setDescription(
        org.mojolang.mojo.openapi.CachedDocument.Builder builderForValue) {
      if (descriptionBuilder_ == null) {
        description_ = builderForValue.build();
        onChanged();
      } else {
        descriptionBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.mojo.openapi.CachedDocument description = 3;</code>
     */
    public Builder mergeDescription(org.mojolang.mojo.openapi.CachedDocument value) {
      if (descriptionBuilder_ == null) {
        if (description_ != null) {
          description_ =
            org.mojolang.mojo.openapi.CachedDocument.newBuilder(description_).mergeFrom(value).buildPartial();
        } else {
          description_ = value;
        }
        onChanged();
      } else {
        descriptionBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.mojo.openapi.CachedDocument description = 3;</code>
     */
    public Builder clearDescription() {
      if (descriptionBuilder_ == null) {
        description_ = null;
        onChanged();
      } else {
        description_ = null;
        descriptionBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.mojo.openapi.CachedDocument description = 3;</code>
     */
    public org.mojolang.mojo.openapi.CachedDocument.Builder getDescriptionBuilder() {
      
      onChanged();
      return getDescriptionFieldBuilder().getBuilder();
    }
    /**
     * <code>.mojo.openapi.CachedDocument description = 3;</code>
     */
    public org.mojolang.mojo.openapi.CachedDocumentOrBuilder getDescriptionOrBuilder() {
      if (descriptionBuilder_ != null) {
        return descriptionBuilder_.getMessageOrBuilder();
      } else {
        return description_ == null ?
            org.mojolang.mojo.openapi.CachedDocument.getDefaultInstance() : description_;
      }
    }
    /**
     * <code>.mojo.openapi.CachedDocument description = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.mojolang.mojo.openapi.CachedDocument, org.mojolang.mojo.openapi.CachedDocument.Builder, org.mojolang.mojo.openapi.CachedDocumentOrBuilder> 
        getDescriptionFieldBuilder() {
      if (descriptionBuilder_ == null) {
        descriptionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.mojolang.mojo.openapi.CachedDocument, org.mojolang.mojo.openapi.CachedDocument.Builder, org.mojolang.mojo.openapi.CachedDocumentOrBuilder>(
                getDescription(),
                getParentForChildren(),
                isClean());
        description_ = null;
      }
      return descriptionBuilder_;
    }

    private org.mojolang.mojo.openapi.ExternalDocument externalDocs_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.mojolang.mojo.openapi.ExternalDocument, org.mojolang.mojo.openapi.ExternalDocument.Builder, org.mojolang.mojo.openapi.ExternalDocumentOrBuilder> externalDocsBuilder_;
    /**
     * <code>.mojo.openapi.ExternalDocument external_docs = 4;</code>
     * @return Whether the externalDocs field is set.
     */
    public boolean hasExternalDocs() {
      return externalDocsBuilder_ != null || externalDocs_ != null;
    }
    /**
     * <code>.mojo.openapi.ExternalDocument external_docs = 4;</code>
     * @return The externalDocs.
     */
    public org.mojolang.mojo.openapi.ExternalDocument getExternalDocs() {
      if (externalDocsBuilder_ == null) {
        return externalDocs_ == null ? org.mojolang.mojo.openapi.ExternalDocument.getDefaultInstance() : externalDocs_;
      } else {
        return externalDocsBuilder_.getMessage();
      }
    }
    /**
     * <code>.mojo.openapi.ExternalDocument external_docs = 4;</code>
     */
    public Builder setExternalDocs(org.mojolang.mojo.openapi.ExternalDocument value) {
      if (externalDocsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        externalDocs_ = value;
        onChanged();
      } else {
        externalDocsBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.mojo.openapi.ExternalDocument external_docs = 4;</code>
     */
    public Builder setExternalDocs(
        org.mojolang.mojo.openapi.ExternalDocument.Builder builderForValue) {
      if (externalDocsBuilder_ == null) {
        externalDocs_ = builderForValue.build();
        onChanged();
      } else {
        externalDocsBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.mojo.openapi.ExternalDocument external_docs = 4;</code>
     */
    public Builder mergeExternalDocs(org.mojolang.mojo.openapi.ExternalDocument value) {
      if (externalDocsBuilder_ == null) {
        if (externalDocs_ != null) {
          externalDocs_ =
            org.mojolang.mojo.openapi.ExternalDocument.newBuilder(externalDocs_).mergeFrom(value).buildPartial();
        } else {
          externalDocs_ = value;
        }
        onChanged();
      } else {
        externalDocsBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.mojo.openapi.ExternalDocument external_docs = 4;</code>
     */
    public Builder clearExternalDocs() {
      if (externalDocsBuilder_ == null) {
        externalDocs_ = null;
        onChanged();
      } else {
        externalDocs_ = null;
        externalDocsBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.mojo.openapi.ExternalDocument external_docs = 4;</code>
     */
    public org.mojolang.mojo.openapi.ExternalDocument.Builder getExternalDocsBuilder() {
      
      onChanged();
      return getExternalDocsFieldBuilder().getBuilder();
    }
    /**
     * <code>.mojo.openapi.ExternalDocument external_docs = 4;</code>
     */
    public org.mojolang.mojo.openapi.ExternalDocumentOrBuilder getExternalDocsOrBuilder() {
      if (externalDocsBuilder_ != null) {
        return externalDocsBuilder_.getMessageOrBuilder();
      } else {
        return externalDocs_ == null ?
            org.mojolang.mojo.openapi.ExternalDocument.getDefaultInstance() : externalDocs_;
      }
    }
    /**
     * <code>.mojo.openapi.ExternalDocument external_docs = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.mojolang.mojo.openapi.ExternalDocument, org.mojolang.mojo.openapi.ExternalDocument.Builder, org.mojolang.mojo.openapi.ExternalDocumentOrBuilder> 
        getExternalDocsFieldBuilder() {
      if (externalDocsBuilder_ == null) {
        externalDocsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.mojolang.mojo.openapi.ExternalDocument, org.mojolang.mojo.openapi.ExternalDocument.Builder, org.mojolang.mojo.openapi.ExternalDocumentOrBuilder>(
                getExternalDocs(),
                getParentForChildren(),
                isClean());
        externalDocs_ = null;
      }
      return externalDocsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:mojo.openapi.Tag)
  }

  // @@protoc_insertion_point(class_scope:mojo.openapi.Tag)
  private static final org.mojolang.mojo.openapi.Tag DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.mojolang.mojo.openapi.Tag();
  }

  public static org.mojolang.mojo.openapi.Tag getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Tag>
      PARSER = new com.google.protobuf.AbstractParser<Tag>() {
    @java.lang.Override
    public Tag parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Tag(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Tag> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Tag> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.mojolang.mojo.openapi.Tag getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

